name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: http://192.168.31.4:10880/actions/checkout@v3
      - uses: http://192.168.31.4:10880/actions/setup-go@v3
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go version
