apiVersion: v1
kind: ConfigMap
metadata:
  name: amber-config
  namespace: amber
data:
  config.yaml: |
    http:
      port: 8000
      host: 0.0.0.0
    
    debug:
      enabled: false
    
    database:
      host: 192.168.81.5
      port: 5432
      user: root
      password: Qwerty123...
      name: amber
      sslmode: disable
    
    redis:
      host: 127.0.0.1
      port: 6379
      password: "123456"
      db: 0
    
    jwks:
      url: "https://auth.leaflow.cn/.well-known/jwks"
    
    metrics:
      enabled: true
      port: 8082
      host: 0.0.0.0
    
    openai:
      api_key: sk-bf4443e2b35f49cf9718827625a704f8
      base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model: qwen-turbo
