// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"rag-new/internal/api/v1"
	"rag-new/internal/base"
	"rag-new/internal/base/conf"
	"rag-new/internal/logger"
	"rag-new/internal/middleware"
	"rag-new/internal/orm"
	"rag-new/internal/router"
	"rag-new/internal/server"
	"rag-new/internal/services"
	"rag-new/internal/services/auth"
	"rag-new/internal/services/jwks"
)

// Injectors from wire.go:

func CreateApp() (*base.Application, error) {
	config := conf.ProviderConfig()
	userController := v1.NewUserController()
	api := router.NewApiRoute(userController)
	loggerLogger := logger.NewZapLogger()
	jwksJWKS := jwks.NewJWKS(config, loggerLogger)
	service := auth.NewAuthService(config, jwksJWKS, loggerLogger)
	middlewareMiddleware := middleware.NewMiddleware(loggerLogger, service)
	engine := server.NewHTTPServer(api, config, middlewareMiddleware)
	xormEngine, err := orm.NewXORM(config)
	if err != nil {
		return nil, err
	}
	servicesService := services.NewService(jwksJWKS, service, loggerLogger)
	application := base.NewApplication(config, engine, loggerLogger, xormEngine, servicesService, middlewareMiddleware)
	return application, nil
}

// wire.go:

var ProviderSet = wire.NewSet(conf.ProviderConfig, logger.NewZapLogger, orm.NewXORM, middleware.Provider, services.Provider, v1.ProviderApiControllerSet, router.ProviderSetRouter, server.NewHTTPServer, base.NewApplication)
