// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"rag-new/internal/api/v1"
	"rag-new/internal/base"
	"rag-new/internal/base/conf"
	"rag-new/internal/logger"
	"rag-new/internal/router"
	"rag-new/internal/server"
)

// Injectors from wire.go:

func CreateApp() (*base.Application, error) {
	config := conf.ProviderConfig()
	userController := v1.NewUserController()
	api := router.NewApiRoute(userController)
	loggerLogger := logger.NewZapLogger()
	engine := server.NewHTTPServer(api, config, loggerLogger)
	application := base.NewApplication(config, engine, loggerLogger)
	return application, nil
}

// wire.go:

var ProviderSet = wire.NewSet(conf.ProviderConfig, v1.ProviderApiControllerSet, logger.NewZapLogger, router.ProviderSetRouter, server.NewHTTPServer, base.NewApplication)
