// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"rag-new/internal/api/v1"
	"rag-new/internal/base"
	"rag-new/internal/base/conf"
	"rag-new/internal/base/logger"
	"rag-new/internal/base/orm"
	"rag-new/internal/base/server"
	"rag-new/internal/middleware"
	"rag-new/internal/router"
	"rag-new/internal/service"
	"rag-new/internal/service/auth"
	"rag-new/internal/service/jwks"
)

// Injectors from wire.go:

func CreateApp() (*base.Application, error) {
	config := conf.ProviderConfig()
	loggerLogger := logger.NewZapLogger()
	jwksJWKS := jwks.NewJWKS(config, loggerLogger)
	authService := auth.NewAuthService(config, jwksJWKS, loggerLogger)
	userController := v1.NewUserController(authService)
	api := router.NewApiRoute(userController)
	middlewareMiddleware := middleware.NewMiddleware(loggerLogger, authService)
	engine := server.NewHTTPServer(api, config, middlewareMiddleware)
	xormEngine, err := orm.NewXORM(config, loggerLogger)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(jwksJWKS, authService, loggerLogger)
	application := base.NewApplication(config, engine, loggerLogger, xormEngine, serviceService, middlewareMiddleware)
	return application, nil
}

// wire.go:

var ProviderSet = wire.NewSet(conf.ProviderConfig, logger.NewZapLogger, orm.NewXORM, middleware.Provider, service.Provider, v1.ProviderApiControllerSet, router.ProviderSetRouter, server.NewHTTPServer, base.NewApplication)
