// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistant(db *gorm.DB, opts ...gen.DOOption) assistant {
	_assistant := assistant{}

	_assistant.assistantDo.UseDB(db, opts...)
	_assistant.assistantDo.UseModel(&entity.Assistant{})

	tableName := _assistant.assistantDo.TableName()
	_assistant.ALL = field.NewAsterisk(tableName)
	_assistant.Id = field.NewUint(tableName, "id")
	_assistant.CreatedAt = field.NewTime(tableName, "created_at")
	_assistant.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistant.Name = field.NewString(tableName, "name")
	_assistant.Prompt = field.NewString(tableName, "prompt")
	_assistant.Description = field.NewString(tableName, "description")
	_assistant.UserId = field.NewString(tableName, "user_id")
	_assistant.LibraryId = field.NewUint(tableName, "library_id")
	_assistant.DisableDefaultPrompt = field.NewBool(tableName, "disable_default_prompt")
	_assistant.DisableMemory = field.NewBool(tableName, "disable_memory")
	_assistant.EnableMemoryForAssistantShare = field.NewBool(tableName, "enable_memory_for_assistant_share")
	_assistant.Library = assistantBelongsToLibrary{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Library", "entity.Library"),
		Document: struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Library.Document", "entity.Document"),
			Library: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Library.Document.Library", "entity.Library"),
			},
		},
	}

	_assistant.fillFieldMap()

	return _assistant
}

type assistant struct {
	assistantDo

	ALL                           field.Asterisk
	Id                            field.Uint
	CreatedAt                     field.Time
	UpdatedAt                     field.Time
	Name                          field.String
	Prompt                        field.String
	Description                   field.String
	UserId                        field.String
	LibraryId                     field.Uint
	DisableDefaultPrompt          field.Bool
	DisableMemory                 field.Bool
	EnableMemoryForAssistantShare field.Bool
	Library                       assistantBelongsToLibrary

	fieldMap map[string]field.Expr
}

func (a assistant) Table(newTableName string) *assistant {
	a.assistantDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistant) As(alias string) *assistant {
	a.assistantDo.DO = *(a.assistantDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistant) updateTableName(table string) *assistant {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.Name = field.NewString(table, "name")
	a.Prompt = field.NewString(table, "prompt")
	a.Description = field.NewString(table, "description")
	a.UserId = field.NewString(table, "user_id")
	a.LibraryId = field.NewUint(table, "library_id")
	a.DisableDefaultPrompt = field.NewBool(table, "disable_default_prompt")
	a.DisableMemory = field.NewBool(table, "disable_memory")
	a.EnableMemoryForAssistantShare = field.NewBool(table, "enable_memory_for_assistant_share")

	a.fillFieldMap()

	return a
}

func (a *assistant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistant) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["prompt"] = a.Prompt
	a.fieldMap["description"] = a.Description
	a.fieldMap["user_id"] = a.UserId
	a.fieldMap["library_id"] = a.LibraryId
	a.fieldMap["disable_default_prompt"] = a.DisableDefaultPrompt
	a.fieldMap["disable_memory"] = a.DisableMemory
	a.fieldMap["enable_memory_for_assistant_share"] = a.EnableMemoryForAssistantShare

}

func (a assistant) clone(db *gorm.DB) assistant {
	a.assistantDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistant) replaceDB(db *gorm.DB) assistant {
	a.assistantDo.ReplaceDB(db)
	return a
}

type assistantBelongsToLibrary struct {
	db *gorm.DB

	field.RelationField

	Document struct {
		field.RelationField
		Library struct {
			field.RelationField
		}
	}
}

func (a assistantBelongsToLibrary) Where(conds ...field.Expr) *assistantBelongsToLibrary {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantBelongsToLibrary) WithContext(ctx context.Context) *assistantBelongsToLibrary {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantBelongsToLibrary) Session(session *gorm.Session) *assistantBelongsToLibrary {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantBelongsToLibrary) Model(m *entity.Assistant) *assistantBelongsToLibraryTx {
	return &assistantBelongsToLibraryTx{a.db.Model(m).Association(a.Name())}
}

type assistantBelongsToLibraryTx struct{ tx *gorm.Association }

func (a assistantBelongsToLibraryTx) Find() (result *entity.Library, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantBelongsToLibraryTx) Append(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantBelongsToLibraryTx) Replace(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantBelongsToLibraryTx) Delete(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantBelongsToLibraryTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantBelongsToLibraryTx) Count() int64 {
	return a.tx.Count()
}

type assistantDo struct{ gen.DO }

type IAssistantDo interface {
	gen.SubQuery
	Debug() IAssistantDo
	WithContext(ctx context.Context) IAssistantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantDo
	WriteDB() IAssistantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantDo
	Not(conds ...gen.Condition) IAssistantDo
	Or(conds ...gen.Condition) IAssistantDo
	Select(conds ...field.Expr) IAssistantDo
	Where(conds ...gen.Condition) IAssistantDo
	Order(conds ...field.Expr) IAssistantDo
	Distinct(cols ...field.Expr) IAssistantDo
	Omit(cols ...field.Expr) IAssistantDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantDo
	Group(cols ...field.Expr) IAssistantDo
	Having(conds ...gen.Condition) IAssistantDo
	Limit(limit int) IAssistantDo
	Offset(offset int) IAssistantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantDo
	Unscoped() IAssistantDo
	Create(values ...*entity.Assistant) error
	CreateInBatches(values []*entity.Assistant, batchSize int) error
	Save(values ...*entity.Assistant) error
	First() (*entity.Assistant, error)
	Take() (*entity.Assistant, error)
	Last() (*entity.Assistant, error)
	Find() ([]*entity.Assistant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Assistant, err error)
	FindInBatches(result *[]*entity.Assistant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Assistant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantDo
	Assign(attrs ...field.AssignExpr) IAssistantDo
	Joins(fields ...field.RelationField) IAssistantDo
	Preload(fields ...field.RelationField) IAssistantDo
	FirstOrInit() (*entity.Assistant, error)
	FirstOrCreate() (*entity.Assistant, error)
	FindByPage(offset int, limit int) (result []*entity.Assistant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantDo) Debug() IAssistantDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantDo) WithContext(ctx context.Context) IAssistantDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantDo) ReadDB() IAssistantDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantDo) WriteDB() IAssistantDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantDo) Session(config *gorm.Session) IAssistantDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantDo) Clauses(conds ...clause.Expression) IAssistantDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantDo) Returning(value interface{}, columns ...string) IAssistantDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantDo) Not(conds ...gen.Condition) IAssistantDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantDo) Or(conds ...gen.Condition) IAssistantDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantDo) Select(conds ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantDo) Where(conds ...gen.Condition) IAssistantDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantDo) Order(conds ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantDo) Distinct(cols ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantDo) Omit(cols ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantDo) Join(table schema.Tabler, on ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantDo) Group(cols ...field.Expr) IAssistantDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantDo) Having(conds ...gen.Condition) IAssistantDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantDo) Limit(limit int) IAssistantDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantDo) Offset(offset int) IAssistantDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantDo) Unscoped() IAssistantDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantDo) Create(values ...*entity.Assistant) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantDo) CreateInBatches(values []*entity.Assistant, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantDo) Save(values ...*entity.Assistant) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantDo) First() (*entity.Assistant, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Assistant), nil
	}
}

func (a assistantDo) Take() (*entity.Assistant, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Assistant), nil
	}
}

func (a assistantDo) Last() (*entity.Assistant, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Assistant), nil
	}
}

func (a assistantDo) Find() ([]*entity.Assistant, error) {
	result, err := a.DO.Find()
	return result.([]*entity.Assistant), err
}

func (a assistantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Assistant, err error) {
	buf := make([]*entity.Assistant, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantDo) FindInBatches(result *[]*entity.Assistant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantDo) Attrs(attrs ...field.AssignExpr) IAssistantDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantDo) Assign(attrs ...field.AssignExpr) IAssistantDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantDo) Joins(fields ...field.RelationField) IAssistantDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantDo) Preload(fields ...field.RelationField) IAssistantDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantDo) FirstOrInit() (*entity.Assistant, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Assistant), nil
	}
}

func (a assistantDo) FirstOrCreate() (*entity.Assistant, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Assistant), nil
	}
}

func (a assistantDo) FindByPage(offset int, limit int) (result []*entity.Assistant, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantDo) Delete(models ...*entity.Assistant) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantDo) withDO(do gen.Dao) *assistantDo {
	a.DO = *do.(*gen.DO)
	return a
}
