// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantApiKey(db *gorm.DB, opts ...gen.DOOption) assistantApiKey {
	_assistantApiKey := assistantApiKey{}

	_assistantApiKey.assistantApiKeyDo.UseDB(db, opts...)
	_assistantApiKey.assistantApiKeyDo.UseModel(&entity.AssistantApiKey{})

	tableName := _assistantApiKey.assistantApiKeyDo.TableName()
	_assistantApiKey.ALL = field.NewAsterisk(tableName)
	_assistantApiKey.Id = field.NewUint(tableName, "id")
	_assistantApiKey.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantApiKey.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantApiKey.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantApiKey.Secret = field.NewString(tableName, "secret")
	_assistantApiKey.Assistant = assistantApiKeyBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_assistantApiKey.fillFieldMap()

	return _assistantApiKey
}

type assistantApiKey struct {
	assistantApiKeyDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	Secret      field.String
	Assistant   assistantApiKeyBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (a assistantApiKey) Table(newTableName string) *assistantApiKey {
	a.assistantApiKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantApiKey) As(alias string) *assistantApiKey {
	a.assistantApiKeyDo.DO = *(a.assistantApiKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantApiKey) updateTableName(table string) *assistantApiKey {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.Secret = field.NewString(table, "secret")

	a.fillFieldMap()

	return a
}

func (a *assistantApiKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantApiKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["secret"] = a.Secret

}

func (a assistantApiKey) clone(db *gorm.DB) assistantApiKey {
	a.assistantApiKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantApiKey) replaceDB(db *gorm.DB) assistantApiKey {
	a.assistantApiKeyDo.ReplaceDB(db)
	return a
}

type assistantApiKeyBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a assistantApiKeyBelongsToAssistant) Where(conds ...field.Expr) *assistantApiKeyBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantApiKeyBelongsToAssistant) WithContext(ctx context.Context) *assistantApiKeyBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantApiKeyBelongsToAssistant) Session(session *gorm.Session) *assistantApiKeyBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantApiKeyBelongsToAssistant) Model(m *entity.AssistantApiKey) *assistantApiKeyBelongsToAssistantTx {
	return &assistantApiKeyBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantApiKeyBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantApiKeyBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantApiKeyBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantApiKeyBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantApiKeyBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantApiKeyBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantApiKeyBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantApiKeyDo struct{ gen.DO }

type IAssistantApiKeyDo interface {
	gen.SubQuery
	Debug() IAssistantApiKeyDo
	WithContext(ctx context.Context) IAssistantApiKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantApiKeyDo
	WriteDB() IAssistantApiKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantApiKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantApiKeyDo
	Not(conds ...gen.Condition) IAssistantApiKeyDo
	Or(conds ...gen.Condition) IAssistantApiKeyDo
	Select(conds ...field.Expr) IAssistantApiKeyDo
	Where(conds ...gen.Condition) IAssistantApiKeyDo
	Order(conds ...field.Expr) IAssistantApiKeyDo
	Distinct(cols ...field.Expr) IAssistantApiKeyDo
	Omit(cols ...field.Expr) IAssistantApiKeyDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo
	Group(cols ...field.Expr) IAssistantApiKeyDo
	Having(conds ...gen.Condition) IAssistantApiKeyDo
	Limit(limit int) IAssistantApiKeyDo
	Offset(offset int) IAssistantApiKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantApiKeyDo
	Unscoped() IAssistantApiKeyDo
	Create(values ...*entity.AssistantApiKey) error
	CreateInBatches(values []*entity.AssistantApiKey, batchSize int) error
	Save(values ...*entity.AssistantApiKey) error
	First() (*entity.AssistantApiKey, error)
	Take() (*entity.AssistantApiKey, error)
	Last() (*entity.AssistantApiKey, error)
	Find() ([]*entity.AssistantApiKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantApiKey, err error)
	FindInBatches(result *[]*entity.AssistantApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantApiKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantApiKeyDo
	Assign(attrs ...field.AssignExpr) IAssistantApiKeyDo
	Joins(fields ...field.RelationField) IAssistantApiKeyDo
	Preload(fields ...field.RelationField) IAssistantApiKeyDo
	FirstOrInit() (*entity.AssistantApiKey, error)
	FirstOrCreate() (*entity.AssistantApiKey, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantApiKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantApiKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantApiKeyDo) Debug() IAssistantApiKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantApiKeyDo) WithContext(ctx context.Context) IAssistantApiKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantApiKeyDo) ReadDB() IAssistantApiKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantApiKeyDo) WriteDB() IAssistantApiKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantApiKeyDo) Session(config *gorm.Session) IAssistantApiKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantApiKeyDo) Clauses(conds ...clause.Expression) IAssistantApiKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantApiKeyDo) Returning(value interface{}, columns ...string) IAssistantApiKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantApiKeyDo) Not(conds ...gen.Condition) IAssistantApiKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantApiKeyDo) Or(conds ...gen.Condition) IAssistantApiKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantApiKeyDo) Select(conds ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantApiKeyDo) Where(conds ...gen.Condition) IAssistantApiKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantApiKeyDo) Order(conds ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantApiKeyDo) Distinct(cols ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantApiKeyDo) Omit(cols ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantApiKeyDo) Join(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantApiKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantApiKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantApiKeyDo) Group(cols ...field.Expr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantApiKeyDo) Having(conds ...gen.Condition) IAssistantApiKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantApiKeyDo) Limit(limit int) IAssistantApiKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantApiKeyDo) Offset(offset int) IAssistantApiKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantApiKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantApiKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantApiKeyDo) Unscoped() IAssistantApiKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantApiKeyDo) Create(values ...*entity.AssistantApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantApiKeyDo) CreateInBatches(values []*entity.AssistantApiKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantApiKeyDo) Save(values ...*entity.AssistantApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantApiKeyDo) First() (*entity.AssistantApiKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantApiKey), nil
	}
}

func (a assistantApiKeyDo) Take() (*entity.AssistantApiKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantApiKey), nil
	}
}

func (a assistantApiKeyDo) Last() (*entity.AssistantApiKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantApiKey), nil
	}
}

func (a assistantApiKeyDo) Find() ([]*entity.AssistantApiKey, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantApiKey), err
}

func (a assistantApiKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantApiKey, err error) {
	buf := make([]*entity.AssistantApiKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantApiKeyDo) FindInBatches(result *[]*entity.AssistantApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantApiKeyDo) Attrs(attrs ...field.AssignExpr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantApiKeyDo) Assign(attrs ...field.AssignExpr) IAssistantApiKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantApiKeyDo) Joins(fields ...field.RelationField) IAssistantApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantApiKeyDo) Preload(fields ...field.RelationField) IAssistantApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantApiKeyDo) FirstOrInit() (*entity.AssistantApiKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantApiKey), nil
	}
}

func (a assistantApiKeyDo) FirstOrCreate() (*entity.AssistantApiKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantApiKey), nil
	}
}

func (a assistantApiKeyDo) FindByPage(offset int, limit int) (result []*entity.AssistantApiKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantApiKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantApiKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantApiKeyDo) Delete(models ...*entity.AssistantApiKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantApiKeyDo) withDO(do gen.Dao) *assistantApiKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
