// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantToken(db *gorm.DB, opts ...gen.DOOption) assistantToken {
	_assistantToken := assistantToken{}

	_assistantToken.assistantTokenDo.UseDB(db, opts...)
	_assistantToken.assistantTokenDo.UseModel(&entity.AssistantToken{})

	tableName := _assistantToken.assistantTokenDo.TableName()
	_assistantToken.ALL = field.NewAsterisk(tableName)
	_assistantToken.Id = field.NewUint(tableName, "id")
	_assistantToken.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantToken.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantToken.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantToken.Token = field.NewString(tableName, "token")
	_assistantToken.Assistant = assistantTokenBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_assistantToken.fillFieldMap()

	return _assistantToken
}

type assistantToken struct {
	assistantTokenDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	Token       field.String
	Assistant   assistantTokenBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (a assistantToken) Table(newTableName string) *assistantToken {
	a.assistantTokenDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantToken) As(alias string) *assistantToken {
	a.assistantTokenDo.DO = *(a.assistantTokenDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantToken) updateTableName(table string) *assistantToken {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.Token = field.NewString(table, "token")

	a.fillFieldMap()

	return a
}

func (a *assistantToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantToken) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["token"] = a.Token

}

func (a assistantToken) clone(db *gorm.DB) assistantToken {
	a.assistantTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantToken) replaceDB(db *gorm.DB) assistantToken {
	a.assistantTokenDo.ReplaceDB(db)
	return a
}

type assistantTokenBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a assistantTokenBelongsToAssistant) Where(conds ...field.Expr) *assistantTokenBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantTokenBelongsToAssistant) WithContext(ctx context.Context) *assistantTokenBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantTokenBelongsToAssistant) Session(session *gorm.Session) *assistantTokenBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantTokenBelongsToAssistant) Model(m *entity.AssistantToken) *assistantTokenBelongsToAssistantTx {
	return &assistantTokenBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantTokenBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantTokenBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantTokenBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantTokenBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantTokenBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantTokenBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantTokenBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantTokenDo struct{ gen.DO }

type IAssistantTokenDo interface {
	gen.SubQuery
	Debug() IAssistantTokenDo
	WithContext(ctx context.Context) IAssistantTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantTokenDo
	WriteDB() IAssistantTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantTokenDo
	Not(conds ...gen.Condition) IAssistantTokenDo
	Or(conds ...gen.Condition) IAssistantTokenDo
	Select(conds ...field.Expr) IAssistantTokenDo
	Where(conds ...gen.Condition) IAssistantTokenDo
	Order(conds ...field.Expr) IAssistantTokenDo
	Distinct(cols ...field.Expr) IAssistantTokenDo
	Omit(cols ...field.Expr) IAssistantTokenDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantTokenDo
	Group(cols ...field.Expr) IAssistantTokenDo
	Having(conds ...gen.Condition) IAssistantTokenDo
	Limit(limit int) IAssistantTokenDo
	Offset(offset int) IAssistantTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantTokenDo
	Unscoped() IAssistantTokenDo
	Create(values ...*entity.AssistantToken) error
	CreateInBatches(values []*entity.AssistantToken, batchSize int) error
	Save(values ...*entity.AssistantToken) error
	First() (*entity.AssistantToken, error)
	Take() (*entity.AssistantToken, error)
	Last() (*entity.AssistantToken, error)
	Find() ([]*entity.AssistantToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantToken, err error)
	FindInBatches(result *[]*entity.AssistantToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantTokenDo
	Assign(attrs ...field.AssignExpr) IAssistantTokenDo
	Joins(fields ...field.RelationField) IAssistantTokenDo
	Preload(fields ...field.RelationField) IAssistantTokenDo
	FirstOrInit() (*entity.AssistantToken, error)
	FirstOrCreate() (*entity.AssistantToken, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantTokenDo) Debug() IAssistantTokenDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantTokenDo) WithContext(ctx context.Context) IAssistantTokenDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantTokenDo) ReadDB() IAssistantTokenDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantTokenDo) WriteDB() IAssistantTokenDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantTokenDo) Session(config *gorm.Session) IAssistantTokenDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantTokenDo) Clauses(conds ...clause.Expression) IAssistantTokenDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantTokenDo) Returning(value interface{}, columns ...string) IAssistantTokenDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantTokenDo) Not(conds ...gen.Condition) IAssistantTokenDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantTokenDo) Or(conds ...gen.Condition) IAssistantTokenDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantTokenDo) Select(conds ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantTokenDo) Where(conds ...gen.Condition) IAssistantTokenDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantTokenDo) Order(conds ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantTokenDo) Distinct(cols ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantTokenDo) Omit(cols ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantTokenDo) Join(table schema.Tabler, on ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantTokenDo) Group(cols ...field.Expr) IAssistantTokenDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantTokenDo) Having(conds ...gen.Condition) IAssistantTokenDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantTokenDo) Limit(limit int) IAssistantTokenDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantTokenDo) Offset(offset int) IAssistantTokenDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantTokenDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantTokenDo) Unscoped() IAssistantTokenDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantTokenDo) Create(values ...*entity.AssistantToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantTokenDo) CreateInBatches(values []*entity.AssistantToken, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantTokenDo) Save(values ...*entity.AssistantToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantTokenDo) First() (*entity.AssistantToken, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantToken), nil
	}
}

func (a assistantTokenDo) Take() (*entity.AssistantToken, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantToken), nil
	}
}

func (a assistantTokenDo) Last() (*entity.AssistantToken, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantToken), nil
	}
}

func (a assistantTokenDo) Find() ([]*entity.AssistantToken, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantToken), err
}

func (a assistantTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantToken, err error) {
	buf := make([]*entity.AssistantToken, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantTokenDo) FindInBatches(result *[]*entity.AssistantToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantTokenDo) Attrs(attrs ...field.AssignExpr) IAssistantTokenDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantTokenDo) Assign(attrs ...field.AssignExpr) IAssistantTokenDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantTokenDo) Joins(fields ...field.RelationField) IAssistantTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantTokenDo) Preload(fields ...field.RelationField) IAssistantTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantTokenDo) FirstOrInit() (*entity.AssistantToken, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantToken), nil
	}
}

func (a assistantTokenDo) FirstOrCreate() (*entity.AssistantToken, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantToken), nil
	}
}

func (a assistantTokenDo) FindByPage(offset int, limit int) (result []*entity.AssistantToken, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantTokenDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantTokenDo) Delete(models ...*entity.AssistantToken) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantTokenDo) withDO(do gen.Dao) *assistantTokenDo {
	a.DO = *do.(*gen.DO)
	return a
}
