// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantKey(db *gorm.DB, opts ...gen.DOOption) assistantKey {
	_assistantKey := assistantKey{}

	_assistantKey.assistantKeyDo.UseDB(db, opts...)
	_assistantKey.assistantKeyDo.UseModel(&entity.AssistantKey{})

	tableName := _assistantKey.assistantKeyDo.TableName()
	_assistantKey.ALL = field.NewAsterisk(tableName)
	_assistantKey.Id = field.NewUint(tableName, "id")
	_assistantKey.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantKey.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantKey.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantKey.Secret = field.NewString(tableName, "secret")
	_assistantKey.Assistant = assistantKeyBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_assistantKey.fillFieldMap()

	return _assistantKey
}

type assistantKey struct {
	assistantKeyDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	Secret      field.String
	Assistant   assistantKeyBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (a assistantKey) Table(newTableName string) *assistantKey {
	a.assistantKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantKey) As(alias string) *assistantKey {
	a.assistantKeyDo.DO = *(a.assistantKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantKey) updateTableName(table string) *assistantKey {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.Secret = field.NewString(table, "secret")

	a.fillFieldMap()

	return a
}

func (a *assistantKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["secret"] = a.Secret

}

func (a assistantKey) clone(db *gorm.DB) assistantKey {
	a.assistantKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantKey) replaceDB(db *gorm.DB) assistantKey {
	a.assistantKeyDo.ReplaceDB(db)
	return a
}

type assistantKeyBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a assistantKeyBelongsToAssistant) Where(conds ...field.Expr) *assistantKeyBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantKeyBelongsToAssistant) WithContext(ctx context.Context) *assistantKeyBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantKeyBelongsToAssistant) Session(session *gorm.Session) *assistantKeyBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantKeyBelongsToAssistant) Model(m *entity.AssistantKey) *assistantKeyBelongsToAssistantTx {
	return &assistantKeyBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantKeyBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantKeyBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantKeyBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantKeyBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantKeyBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantKeyBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantKeyBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantKeyDo struct{ gen.DO }

type IAssistantKeyDo interface {
	gen.SubQuery
	Debug() IAssistantKeyDo
	WithContext(ctx context.Context) IAssistantKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantKeyDo
	WriteDB() IAssistantKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantKeyDo
	Not(conds ...gen.Condition) IAssistantKeyDo
	Or(conds ...gen.Condition) IAssistantKeyDo
	Select(conds ...field.Expr) IAssistantKeyDo
	Where(conds ...gen.Condition) IAssistantKeyDo
	Order(conds ...field.Expr) IAssistantKeyDo
	Distinct(cols ...field.Expr) IAssistantKeyDo
	Omit(cols ...field.Expr) IAssistantKeyDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantKeyDo
	Group(cols ...field.Expr) IAssistantKeyDo
	Having(conds ...gen.Condition) IAssistantKeyDo
	Limit(limit int) IAssistantKeyDo
	Offset(offset int) IAssistantKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantKeyDo
	Unscoped() IAssistantKeyDo
	Create(values ...*entity.AssistantKey) error
	CreateInBatches(values []*entity.AssistantKey, batchSize int) error
	Save(values ...*entity.AssistantKey) error
	First() (*entity.AssistantKey, error)
	Take() (*entity.AssistantKey, error)
	Last() (*entity.AssistantKey, error)
	Find() ([]*entity.AssistantKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantKey, err error)
	FindInBatches(result *[]*entity.AssistantKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantKeyDo
	Assign(attrs ...field.AssignExpr) IAssistantKeyDo
	Joins(fields ...field.RelationField) IAssistantKeyDo
	Preload(fields ...field.RelationField) IAssistantKeyDo
	FirstOrInit() (*entity.AssistantKey, error)
	FirstOrCreate() (*entity.AssistantKey, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantKeyDo) Debug() IAssistantKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantKeyDo) WithContext(ctx context.Context) IAssistantKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantKeyDo) ReadDB() IAssistantKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantKeyDo) WriteDB() IAssistantKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantKeyDo) Session(config *gorm.Session) IAssistantKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantKeyDo) Clauses(conds ...clause.Expression) IAssistantKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantKeyDo) Returning(value interface{}, columns ...string) IAssistantKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantKeyDo) Not(conds ...gen.Condition) IAssistantKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantKeyDo) Or(conds ...gen.Condition) IAssistantKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantKeyDo) Select(conds ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantKeyDo) Where(conds ...gen.Condition) IAssistantKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantKeyDo) Order(conds ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantKeyDo) Distinct(cols ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantKeyDo) Omit(cols ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantKeyDo) Join(table schema.Tabler, on ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantKeyDo) Group(cols ...field.Expr) IAssistantKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantKeyDo) Having(conds ...gen.Condition) IAssistantKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantKeyDo) Limit(limit int) IAssistantKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantKeyDo) Offset(offset int) IAssistantKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantKeyDo) Unscoped() IAssistantKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantKeyDo) Create(values ...*entity.AssistantKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantKeyDo) CreateInBatches(values []*entity.AssistantKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantKeyDo) Save(values ...*entity.AssistantKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantKeyDo) First() (*entity.AssistantKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantKey), nil
	}
}

func (a assistantKeyDo) Take() (*entity.AssistantKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantKey), nil
	}
}

func (a assistantKeyDo) Last() (*entity.AssistantKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantKey), nil
	}
}

func (a assistantKeyDo) Find() ([]*entity.AssistantKey, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantKey), err
}

func (a assistantKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantKey, err error) {
	buf := make([]*entity.AssistantKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantKeyDo) FindInBatches(result *[]*entity.AssistantKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantKeyDo) Attrs(attrs ...field.AssignExpr) IAssistantKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantKeyDo) Assign(attrs ...field.AssignExpr) IAssistantKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantKeyDo) Joins(fields ...field.RelationField) IAssistantKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantKeyDo) Preload(fields ...field.RelationField) IAssistantKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantKeyDo) FirstOrInit() (*entity.AssistantKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantKey), nil
	}
}

func (a assistantKeyDo) FirstOrCreate() (*entity.AssistantKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantKey), nil
	}
}

func (a assistantKeyDo) FindByPage(offset int, limit int) (result []*entity.AssistantKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantKeyDo) Delete(models ...*entity.AssistantKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantKeyDo) withDO(do gen.Dao) *assistantKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
