// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantTool(db *gorm.DB, opts ...gen.DOOption) assistantTool {
	_assistantTool := assistantTool{}

	_assistantTool.assistantToolDo.UseDB(db, opts...)
	_assistantTool.assistantToolDo.UseModel(&entity.AssistantTool{})

	tableName := _assistantTool.assistantToolDo.TableName()
	_assistantTool.ALL = field.NewAsterisk(tableName)
	_assistantTool.Id = field.NewUint(tableName, "id")
	_assistantTool.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantTool.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantTool.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantTool.ToolId = field.NewUint(tableName, "tool_id")
	_assistantTool.Assistant = assistantToolBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_assistantTool.Tool = assistantToolBelongsToTool{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tool", "entity.Tool"),
	}

	_assistantTool.fillFieldMap()

	return _assistantTool
}

type assistantTool struct {
	assistantToolDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	ToolId      field.Uint
	Assistant   assistantToolBelongsToAssistant

	Tool assistantToolBelongsToTool

	fieldMap map[string]field.Expr
}

func (a assistantTool) Table(newTableName string) *assistantTool {
	a.assistantToolDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantTool) As(alias string) *assistantTool {
	a.assistantToolDo.DO = *(a.assistantToolDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantTool) updateTableName(table string) *assistantTool {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.ToolId = field.NewUint(table, "tool_id")

	a.fillFieldMap()

	return a
}

func (a *assistantTool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantTool) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["tool_id"] = a.ToolId

}

func (a assistantTool) clone(db *gorm.DB) assistantTool {
	a.assistantToolDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantTool) replaceDB(db *gorm.DB) assistantTool {
	a.assistantToolDo.ReplaceDB(db)
	return a
}

type assistantToolBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a assistantToolBelongsToAssistant) Where(conds ...field.Expr) *assistantToolBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantToolBelongsToAssistant) WithContext(ctx context.Context) *assistantToolBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantToolBelongsToAssistant) Session(session *gorm.Session) *assistantToolBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantToolBelongsToAssistant) Model(m *entity.AssistantTool) *assistantToolBelongsToAssistantTx {
	return &assistantToolBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantToolBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantToolBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantToolBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantToolBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantToolBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantToolBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantToolBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantToolBelongsToTool struct {
	db *gorm.DB

	field.RelationField
}

func (a assistantToolBelongsToTool) Where(conds ...field.Expr) *assistantToolBelongsToTool {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantToolBelongsToTool) WithContext(ctx context.Context) *assistantToolBelongsToTool {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantToolBelongsToTool) Session(session *gorm.Session) *assistantToolBelongsToTool {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantToolBelongsToTool) Model(m *entity.AssistantTool) *assistantToolBelongsToToolTx {
	return &assistantToolBelongsToToolTx{a.db.Model(m).Association(a.Name())}
}

type assistantToolBelongsToToolTx struct{ tx *gorm.Association }

func (a assistantToolBelongsToToolTx) Find() (result *entity.Tool, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantToolBelongsToToolTx) Append(values ...*entity.Tool) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantToolBelongsToToolTx) Replace(values ...*entity.Tool) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantToolBelongsToToolTx) Delete(values ...*entity.Tool) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantToolBelongsToToolTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantToolBelongsToToolTx) Count() int64 {
	return a.tx.Count()
}

type assistantToolDo struct{ gen.DO }

type IAssistantToolDo interface {
	gen.SubQuery
	Debug() IAssistantToolDo
	WithContext(ctx context.Context) IAssistantToolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantToolDo
	WriteDB() IAssistantToolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantToolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantToolDo
	Not(conds ...gen.Condition) IAssistantToolDo
	Or(conds ...gen.Condition) IAssistantToolDo
	Select(conds ...field.Expr) IAssistantToolDo
	Where(conds ...gen.Condition) IAssistantToolDo
	Order(conds ...field.Expr) IAssistantToolDo
	Distinct(cols ...field.Expr) IAssistantToolDo
	Omit(cols ...field.Expr) IAssistantToolDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantToolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantToolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantToolDo
	Group(cols ...field.Expr) IAssistantToolDo
	Having(conds ...gen.Condition) IAssistantToolDo
	Limit(limit int) IAssistantToolDo
	Offset(offset int) IAssistantToolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantToolDo
	Unscoped() IAssistantToolDo
	Create(values ...*entity.AssistantTool) error
	CreateInBatches(values []*entity.AssistantTool, batchSize int) error
	Save(values ...*entity.AssistantTool) error
	First() (*entity.AssistantTool, error)
	Take() (*entity.AssistantTool, error)
	Last() (*entity.AssistantTool, error)
	Find() ([]*entity.AssistantTool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantTool, err error)
	FindInBatches(result *[]*entity.AssistantTool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantTool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantToolDo
	Assign(attrs ...field.AssignExpr) IAssistantToolDo
	Joins(fields ...field.RelationField) IAssistantToolDo
	Preload(fields ...field.RelationField) IAssistantToolDo
	FirstOrInit() (*entity.AssistantTool, error)
	FirstOrCreate() (*entity.AssistantTool, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantTool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantToolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantToolDo) Debug() IAssistantToolDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantToolDo) WithContext(ctx context.Context) IAssistantToolDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantToolDo) ReadDB() IAssistantToolDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantToolDo) WriteDB() IAssistantToolDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantToolDo) Session(config *gorm.Session) IAssistantToolDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantToolDo) Clauses(conds ...clause.Expression) IAssistantToolDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantToolDo) Returning(value interface{}, columns ...string) IAssistantToolDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantToolDo) Not(conds ...gen.Condition) IAssistantToolDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantToolDo) Or(conds ...gen.Condition) IAssistantToolDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantToolDo) Select(conds ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantToolDo) Where(conds ...gen.Condition) IAssistantToolDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantToolDo) Order(conds ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantToolDo) Distinct(cols ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantToolDo) Omit(cols ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantToolDo) Join(table schema.Tabler, on ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantToolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantToolDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantToolDo) Group(cols ...field.Expr) IAssistantToolDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantToolDo) Having(conds ...gen.Condition) IAssistantToolDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantToolDo) Limit(limit int) IAssistantToolDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantToolDo) Offset(offset int) IAssistantToolDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantToolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantToolDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantToolDo) Unscoped() IAssistantToolDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantToolDo) Create(values ...*entity.AssistantTool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantToolDo) CreateInBatches(values []*entity.AssistantTool, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantToolDo) Save(values ...*entity.AssistantTool) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantToolDo) First() (*entity.AssistantTool, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantTool), nil
	}
}

func (a assistantToolDo) Take() (*entity.AssistantTool, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantTool), nil
	}
}

func (a assistantToolDo) Last() (*entity.AssistantTool, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantTool), nil
	}
}

func (a assistantToolDo) Find() ([]*entity.AssistantTool, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantTool), err
}

func (a assistantToolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantTool, err error) {
	buf := make([]*entity.AssistantTool, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantToolDo) FindInBatches(result *[]*entity.AssistantTool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantToolDo) Attrs(attrs ...field.AssignExpr) IAssistantToolDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantToolDo) Assign(attrs ...field.AssignExpr) IAssistantToolDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantToolDo) Joins(fields ...field.RelationField) IAssistantToolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantToolDo) Preload(fields ...field.RelationField) IAssistantToolDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantToolDo) FirstOrInit() (*entity.AssistantTool, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantTool), nil
	}
}

func (a assistantToolDo) FirstOrCreate() (*entity.AssistantTool, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantTool), nil
	}
}

func (a assistantToolDo) FindByPage(offset int, limit int) (result []*entity.AssistantTool, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantToolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantToolDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantToolDo) Delete(models ...*entity.AssistantTool) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantToolDo) withDO(do gen.Dao) *assistantToolDo {
	a.DO = *do.(*gen.DO)
	return a
}
