// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantShare(db *gorm.DB, opts ...gen.DOOption) assistantShare {
	_assistantShare := assistantShare{}

	_assistantShare.assistantShareDo.UseDB(db, opts...)
	_assistantShare.assistantShareDo.UseModel(&entity.AssistantShare{})

	tableName := _assistantShare.assistantShareDo.TableName()
	_assistantShare.ALL = field.NewAsterisk(tableName)
	_assistantShare.Id = field.NewUint(tableName, "id")
	_assistantShare.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantShare.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantShare.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantShare.Token = field.NewString(tableName, "token")
	_assistantShare.Assistant = assistantShareBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
	}

	_assistantShare.fillFieldMap()

	return _assistantShare
}

type assistantShare struct {
	assistantShareDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	Token       field.String
	Assistant   assistantShareBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (a assistantShare) Table(newTableName string) *assistantShare {
	a.assistantShareDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantShare) As(alias string) *assistantShare {
	a.assistantShareDo.DO = *(a.assistantShareDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantShare) updateTableName(table string) *assistantShare {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.Token = field.NewString(table, "token")

	a.fillFieldMap()

	return a
}

func (a *assistantShare) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantShare) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["token"] = a.Token

}

func (a assistantShare) clone(db *gorm.DB) assistantShare {
	a.assistantShareDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantShare) replaceDB(db *gorm.DB) assistantShare {
	a.assistantShareDo.ReplaceDB(db)
	return a
}

type assistantShareBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField
}

func (a assistantShareBelongsToAssistant) Where(conds ...field.Expr) *assistantShareBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantShareBelongsToAssistant) WithContext(ctx context.Context) *assistantShareBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantShareBelongsToAssistant) Session(session *gorm.Session) *assistantShareBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantShareBelongsToAssistant) Model(m *entity.AssistantShare) *assistantShareBelongsToAssistantTx {
	return &assistantShareBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantShareBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantShareBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantShareBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantShareBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantShareBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantShareBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantShareBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantShareDo struct{ gen.DO }

type IAssistantShareDo interface {
	gen.SubQuery
	Debug() IAssistantShareDo
	WithContext(ctx context.Context) IAssistantShareDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantShareDo
	WriteDB() IAssistantShareDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantShareDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantShareDo
	Not(conds ...gen.Condition) IAssistantShareDo
	Or(conds ...gen.Condition) IAssistantShareDo
	Select(conds ...field.Expr) IAssistantShareDo
	Where(conds ...gen.Condition) IAssistantShareDo
	Order(conds ...field.Expr) IAssistantShareDo
	Distinct(cols ...field.Expr) IAssistantShareDo
	Omit(cols ...field.Expr) IAssistantShareDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantShareDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantShareDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantShareDo
	Group(cols ...field.Expr) IAssistantShareDo
	Having(conds ...gen.Condition) IAssistantShareDo
	Limit(limit int) IAssistantShareDo
	Offset(offset int) IAssistantShareDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantShareDo
	Unscoped() IAssistantShareDo
	Create(values ...*entity.AssistantShare) error
	CreateInBatches(values []*entity.AssistantShare, batchSize int) error
	Save(values ...*entity.AssistantShare) error
	First() (*entity.AssistantShare, error)
	Take() (*entity.AssistantShare, error)
	Last() (*entity.AssistantShare, error)
	Find() ([]*entity.AssistantShare, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantShare, err error)
	FindInBatches(result *[]*entity.AssistantShare, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantShare) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantShareDo
	Assign(attrs ...field.AssignExpr) IAssistantShareDo
	Joins(fields ...field.RelationField) IAssistantShareDo
	Preload(fields ...field.RelationField) IAssistantShareDo
	FirstOrInit() (*entity.AssistantShare, error)
	FirstOrCreate() (*entity.AssistantShare, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantShare, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantShareDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantShareDo) Debug() IAssistantShareDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantShareDo) WithContext(ctx context.Context) IAssistantShareDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantShareDo) ReadDB() IAssistantShareDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantShareDo) WriteDB() IAssistantShareDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantShareDo) Session(config *gorm.Session) IAssistantShareDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantShareDo) Clauses(conds ...clause.Expression) IAssistantShareDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantShareDo) Returning(value interface{}, columns ...string) IAssistantShareDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantShareDo) Not(conds ...gen.Condition) IAssistantShareDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantShareDo) Or(conds ...gen.Condition) IAssistantShareDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantShareDo) Select(conds ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantShareDo) Where(conds ...gen.Condition) IAssistantShareDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantShareDo) Order(conds ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantShareDo) Distinct(cols ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantShareDo) Omit(cols ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantShareDo) Join(table schema.Tabler, on ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantShareDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantShareDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantShareDo) Group(cols ...field.Expr) IAssistantShareDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantShareDo) Having(conds ...gen.Condition) IAssistantShareDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantShareDo) Limit(limit int) IAssistantShareDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantShareDo) Offset(offset int) IAssistantShareDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantShareDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantShareDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantShareDo) Unscoped() IAssistantShareDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantShareDo) Create(values ...*entity.AssistantShare) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantShareDo) CreateInBatches(values []*entity.AssistantShare, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantShareDo) Save(values ...*entity.AssistantShare) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantShareDo) First() (*entity.AssistantShare, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantShare), nil
	}
}

func (a assistantShareDo) Take() (*entity.AssistantShare, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantShare), nil
	}
}

func (a assistantShareDo) Last() (*entity.AssistantShare, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantShare), nil
	}
}

func (a assistantShareDo) Find() ([]*entity.AssistantShare, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantShare), err
}

func (a assistantShareDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantShare, err error) {
	buf := make([]*entity.AssistantShare, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantShareDo) FindInBatches(result *[]*entity.AssistantShare, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantShareDo) Attrs(attrs ...field.AssignExpr) IAssistantShareDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantShareDo) Assign(attrs ...field.AssignExpr) IAssistantShareDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantShareDo) Joins(fields ...field.RelationField) IAssistantShareDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantShareDo) Preload(fields ...field.RelationField) IAssistantShareDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantShareDo) FirstOrInit() (*entity.AssistantShare, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantShare), nil
	}
}

func (a assistantShareDo) FirstOrCreate() (*entity.AssistantShare, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantShare), nil
	}
}

func (a assistantShareDo) FindByPage(offset int, limit int) (result []*entity.AssistantShare, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantShareDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantShareDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantShareDo) Delete(models ...*entity.AssistantShare) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantShareDo) withDO(do gen.Dao) *assistantShareDo {
	a.DO = *do.(*gen.DO)
	return a
}
