// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newAssistantFavorites(db *gorm.DB, opts ...gen.DOOption) assistantFavorites {
	_assistantFavorites := assistantFavorites{}

	_assistantFavorites.assistantFavoritesDo.UseDB(db, opts...)
	_assistantFavorites.assistantFavoritesDo.UseModel(&entity.AssistantFavorites{})

	tableName := _assistantFavorites.assistantFavoritesDo.TableName()
	_assistantFavorites.ALL = field.NewAsterisk(tableName)
	_assistantFavorites.Id = field.NewUint(tableName, "id")
	_assistantFavorites.CreatedAt = field.NewTime(tableName, "created_at")
	_assistantFavorites.UpdatedAt = field.NewTime(tableName, "updated_at")
	_assistantFavorites.AssistantId = field.NewUint(tableName, "assistant_id")
	_assistantFavorites.UserId = field.NewString(tableName, "user_id")
	_assistantFavorites.Assistant = assistantFavoritesBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_assistantFavorites.fillFieldMap()

	return _assistantFavorites
}

type assistantFavorites struct {
	assistantFavoritesDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	UserId      field.String
	Assistant   assistantFavoritesBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (a assistantFavorites) Table(newTableName string) *assistantFavorites {
	a.assistantFavoritesDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assistantFavorites) As(alias string) *assistantFavorites {
	a.assistantFavoritesDo.DO = *(a.assistantFavoritesDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assistantFavorites) updateTableName(table string) *assistantFavorites {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.AssistantId = field.NewUint(table, "assistant_id")
	a.UserId = field.NewString(table, "user_id")

	a.fillFieldMap()

	return a
}

func (a *assistantFavorites) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assistantFavorites) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.Id
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["assistant_id"] = a.AssistantId
	a.fieldMap["user_id"] = a.UserId

}

func (a assistantFavorites) clone(db *gorm.DB) assistantFavorites {
	a.assistantFavoritesDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assistantFavorites) replaceDB(db *gorm.DB) assistantFavorites {
	a.assistantFavoritesDo.ReplaceDB(db)
	return a
}

type assistantFavoritesBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a assistantFavoritesBelongsToAssistant) Where(conds ...field.Expr) *assistantFavoritesBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a assistantFavoritesBelongsToAssistant) WithContext(ctx context.Context) *assistantFavoritesBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a assistantFavoritesBelongsToAssistant) Session(session *gorm.Session) *assistantFavoritesBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a assistantFavoritesBelongsToAssistant) Model(m *entity.AssistantFavorites) *assistantFavoritesBelongsToAssistantTx {
	return &assistantFavoritesBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type assistantFavoritesBelongsToAssistantTx struct{ tx *gorm.Association }

func (a assistantFavoritesBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a assistantFavoritesBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a assistantFavoritesBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a assistantFavoritesBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a assistantFavoritesBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a assistantFavoritesBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type assistantFavoritesDo struct{ gen.DO }

type IAssistantFavoritesDo interface {
	gen.SubQuery
	Debug() IAssistantFavoritesDo
	WithContext(ctx context.Context) IAssistantFavoritesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssistantFavoritesDo
	WriteDB() IAssistantFavoritesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssistantFavoritesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssistantFavoritesDo
	Not(conds ...gen.Condition) IAssistantFavoritesDo
	Or(conds ...gen.Condition) IAssistantFavoritesDo
	Select(conds ...field.Expr) IAssistantFavoritesDo
	Where(conds ...gen.Condition) IAssistantFavoritesDo
	Order(conds ...field.Expr) IAssistantFavoritesDo
	Distinct(cols ...field.Expr) IAssistantFavoritesDo
	Omit(cols ...field.Expr) IAssistantFavoritesDo
	Join(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo
	Group(cols ...field.Expr) IAssistantFavoritesDo
	Having(conds ...gen.Condition) IAssistantFavoritesDo
	Limit(limit int) IAssistantFavoritesDo
	Offset(offset int) IAssistantFavoritesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantFavoritesDo
	Unscoped() IAssistantFavoritesDo
	Create(values ...*entity.AssistantFavorites) error
	CreateInBatches(values []*entity.AssistantFavorites, batchSize int) error
	Save(values ...*entity.AssistantFavorites) error
	First() (*entity.AssistantFavorites, error)
	Take() (*entity.AssistantFavorites, error)
	Last() (*entity.AssistantFavorites, error)
	Find() ([]*entity.AssistantFavorites, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantFavorites, err error)
	FindInBatches(result *[]*entity.AssistantFavorites, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.AssistantFavorites) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssistantFavoritesDo
	Assign(attrs ...field.AssignExpr) IAssistantFavoritesDo
	Joins(fields ...field.RelationField) IAssistantFavoritesDo
	Preload(fields ...field.RelationField) IAssistantFavoritesDo
	FirstOrInit() (*entity.AssistantFavorites, error)
	FirstOrCreate() (*entity.AssistantFavorites, error)
	FindByPage(offset int, limit int) (result []*entity.AssistantFavorites, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssistantFavoritesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assistantFavoritesDo) Debug() IAssistantFavoritesDo {
	return a.withDO(a.DO.Debug())
}

func (a assistantFavoritesDo) WithContext(ctx context.Context) IAssistantFavoritesDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assistantFavoritesDo) ReadDB() IAssistantFavoritesDo {
	return a.Clauses(dbresolver.Read)
}

func (a assistantFavoritesDo) WriteDB() IAssistantFavoritesDo {
	return a.Clauses(dbresolver.Write)
}

func (a assistantFavoritesDo) Session(config *gorm.Session) IAssistantFavoritesDo {
	return a.withDO(a.DO.Session(config))
}

func (a assistantFavoritesDo) Clauses(conds ...clause.Expression) IAssistantFavoritesDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assistantFavoritesDo) Returning(value interface{}, columns ...string) IAssistantFavoritesDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assistantFavoritesDo) Not(conds ...gen.Condition) IAssistantFavoritesDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assistantFavoritesDo) Or(conds ...gen.Condition) IAssistantFavoritesDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assistantFavoritesDo) Select(conds ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assistantFavoritesDo) Where(conds ...gen.Condition) IAssistantFavoritesDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assistantFavoritesDo) Order(conds ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assistantFavoritesDo) Distinct(cols ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assistantFavoritesDo) Omit(cols ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assistantFavoritesDo) Join(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assistantFavoritesDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assistantFavoritesDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assistantFavoritesDo) Group(cols ...field.Expr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assistantFavoritesDo) Having(conds ...gen.Condition) IAssistantFavoritesDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assistantFavoritesDo) Limit(limit int) IAssistantFavoritesDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assistantFavoritesDo) Offset(offset int) IAssistantFavoritesDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assistantFavoritesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssistantFavoritesDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assistantFavoritesDo) Unscoped() IAssistantFavoritesDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assistantFavoritesDo) Create(values ...*entity.AssistantFavorites) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assistantFavoritesDo) CreateInBatches(values []*entity.AssistantFavorites, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assistantFavoritesDo) Save(values ...*entity.AssistantFavorites) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assistantFavoritesDo) First() (*entity.AssistantFavorites, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantFavorites), nil
	}
}

func (a assistantFavoritesDo) Take() (*entity.AssistantFavorites, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantFavorites), nil
	}
}

func (a assistantFavoritesDo) Last() (*entity.AssistantFavorites, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantFavorites), nil
	}
}

func (a assistantFavoritesDo) Find() ([]*entity.AssistantFavorites, error) {
	result, err := a.DO.Find()
	return result.([]*entity.AssistantFavorites), err
}

func (a assistantFavoritesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.AssistantFavorites, err error) {
	buf := make([]*entity.AssistantFavorites, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assistantFavoritesDo) FindInBatches(result *[]*entity.AssistantFavorites, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assistantFavoritesDo) Attrs(attrs ...field.AssignExpr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assistantFavoritesDo) Assign(attrs ...field.AssignExpr) IAssistantFavoritesDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assistantFavoritesDo) Joins(fields ...field.RelationField) IAssistantFavoritesDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assistantFavoritesDo) Preload(fields ...field.RelationField) IAssistantFavoritesDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assistantFavoritesDo) FirstOrInit() (*entity.AssistantFavorites, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantFavorites), nil
	}
}

func (a assistantFavoritesDo) FirstOrCreate() (*entity.AssistantFavorites, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.AssistantFavorites), nil
	}
}

func (a assistantFavoritesDo) FindByPage(offset int, limit int) (result []*entity.AssistantFavorites, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assistantFavoritesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assistantFavoritesDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assistantFavoritesDo) Delete(models ...*entity.AssistantFavorites) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assistantFavoritesDo) withDO(do gen.Dao) *assistantFavoritesDo {
	a.DO = *do.(*gen.DO)
	return a
}
