// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newDocumentChunk(db *gorm.DB, opts ...gen.DOOption) documentChunk {
	_documentChunk := documentChunk{}

	_documentChunk.documentChunkDo.UseDB(db, opts...)
	_documentChunk.documentChunkDo.UseModel(&entity.DocumentChunk{})

	tableName := _documentChunk.documentChunkDo.TableName()
	_documentChunk.ALL = field.NewAsterisk(tableName)
	_documentChunk.Id = field.NewUint(tableName, "id")
	_documentChunk.CreatedAt = field.NewTime(tableName, "created_at")
	_documentChunk.UpdatedAt = field.NewTime(tableName, "updated_at")
	_documentChunk.Content = field.NewString(tableName, "content")
	_documentChunk.Order_ = field.NewInt(tableName, "order")
	_documentChunk.DocumentId = field.NewUint(tableName, "document_id")
	_documentChunk.LibraryId = field.NewUint(tableName, "library_id")
	_documentChunk.Chunked = field.NewBool(tableName, "chunked")
	_documentChunk.Library = documentChunkBelongsToLibrary{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Library", "entity.Library"),
		Document: struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
			File struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Library.Document", "entity.Document"),
			Library: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Library.Document.Library", "entity.Library"),
			},
			File: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Library.Document.File", "entity.File"),
			},
		},
	}

	_documentChunk.fillFieldMap()

	return _documentChunk
}

type documentChunk struct {
	documentChunkDo

	ALL        field.Asterisk
	Id         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	Content    field.String
	Order_     field.Int
	DocumentId field.Uint
	LibraryId  field.Uint
	Chunked    field.Bool
	Library    documentChunkBelongsToLibrary

	fieldMap map[string]field.Expr
}

func (d documentChunk) Table(newTableName string) *documentChunk {
	d.documentChunkDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d documentChunk) As(alias string) *documentChunk {
	d.documentChunkDo.DO = *(d.documentChunkDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *documentChunk) updateTableName(table string) *documentChunk {
	d.ALL = field.NewAsterisk(table)
	d.Id = field.NewUint(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.Content = field.NewString(table, "content")
	d.Order_ = field.NewInt(table, "order")
	d.DocumentId = field.NewUint(table, "document_id")
	d.LibraryId = field.NewUint(table, "library_id")
	d.Chunked = field.NewBool(table, "chunked")

	d.fillFieldMap()

	return d
}

func (d *documentChunk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *documentChunk) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.Id
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["content"] = d.Content
	d.fieldMap["order"] = d.Order_
	d.fieldMap["document_id"] = d.DocumentId
	d.fieldMap["library_id"] = d.LibraryId
	d.fieldMap["chunked"] = d.Chunked

}

func (d documentChunk) clone(db *gorm.DB) documentChunk {
	d.documentChunkDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d documentChunk) replaceDB(db *gorm.DB) documentChunk {
	d.documentChunkDo.ReplaceDB(db)
	return d
}

type documentChunkBelongsToLibrary struct {
	db *gorm.DB

	field.RelationField

	Document struct {
		field.RelationField
		Library struct {
			field.RelationField
		}
		File struct {
			field.RelationField
		}
	}
}

func (a documentChunkBelongsToLibrary) Where(conds ...field.Expr) *documentChunkBelongsToLibrary {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a documentChunkBelongsToLibrary) WithContext(ctx context.Context) *documentChunkBelongsToLibrary {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a documentChunkBelongsToLibrary) Session(session *gorm.Session) *documentChunkBelongsToLibrary {
	a.db = a.db.Session(session)
	return &a
}

func (a documentChunkBelongsToLibrary) Model(m *entity.DocumentChunk) *documentChunkBelongsToLibraryTx {
	return &documentChunkBelongsToLibraryTx{a.db.Model(m).Association(a.Name())}
}

type documentChunkBelongsToLibraryTx struct{ tx *gorm.Association }

func (a documentChunkBelongsToLibraryTx) Find() (result *entity.Library, err error) {
	return result, a.tx.Find(&result)
}

func (a documentChunkBelongsToLibraryTx) Append(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a documentChunkBelongsToLibraryTx) Replace(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a documentChunkBelongsToLibraryTx) Delete(values ...*entity.Library) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a documentChunkBelongsToLibraryTx) Clear() error {
	return a.tx.Clear()
}

func (a documentChunkBelongsToLibraryTx) Count() int64 {
	return a.tx.Count()
}

type documentChunkDo struct{ gen.DO }

type IDocumentChunkDo interface {
	gen.SubQuery
	Debug() IDocumentChunkDo
	WithContext(ctx context.Context) IDocumentChunkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDocumentChunkDo
	WriteDB() IDocumentChunkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDocumentChunkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDocumentChunkDo
	Not(conds ...gen.Condition) IDocumentChunkDo
	Or(conds ...gen.Condition) IDocumentChunkDo
	Select(conds ...field.Expr) IDocumentChunkDo
	Where(conds ...gen.Condition) IDocumentChunkDo
	Order(conds ...field.Expr) IDocumentChunkDo
	Distinct(cols ...field.Expr) IDocumentChunkDo
	Omit(cols ...field.Expr) IDocumentChunkDo
	Join(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	Group(cols ...field.Expr) IDocumentChunkDo
	Having(conds ...gen.Condition) IDocumentChunkDo
	Limit(limit int) IDocumentChunkDo
	Offset(offset int) IDocumentChunkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentChunkDo
	Unscoped() IDocumentChunkDo
	Create(values ...*entity.DocumentChunk) error
	CreateInBatches(values []*entity.DocumentChunk, batchSize int) error
	Save(values ...*entity.DocumentChunk) error
	First() (*entity.DocumentChunk, error)
	Take() (*entity.DocumentChunk, error)
	Last() (*entity.DocumentChunk, error)
	Find() ([]*entity.DocumentChunk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DocumentChunk, err error)
	FindInBatches(result *[]*entity.DocumentChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.DocumentChunk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDocumentChunkDo
	Assign(attrs ...field.AssignExpr) IDocumentChunkDo
	Joins(fields ...field.RelationField) IDocumentChunkDo
	Preload(fields ...field.RelationField) IDocumentChunkDo
	FirstOrInit() (*entity.DocumentChunk, error)
	FirstOrCreate() (*entity.DocumentChunk, error)
	FindByPage(offset int, limit int) (result []*entity.DocumentChunk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDocumentChunkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d documentChunkDo) Debug() IDocumentChunkDo {
	return d.withDO(d.DO.Debug())
}

func (d documentChunkDo) WithContext(ctx context.Context) IDocumentChunkDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d documentChunkDo) ReadDB() IDocumentChunkDo {
	return d.Clauses(dbresolver.Read)
}

func (d documentChunkDo) WriteDB() IDocumentChunkDo {
	return d.Clauses(dbresolver.Write)
}

func (d documentChunkDo) Session(config *gorm.Session) IDocumentChunkDo {
	return d.withDO(d.DO.Session(config))
}

func (d documentChunkDo) Clauses(conds ...clause.Expression) IDocumentChunkDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d documentChunkDo) Returning(value interface{}, columns ...string) IDocumentChunkDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d documentChunkDo) Not(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d documentChunkDo) Or(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d documentChunkDo) Select(conds ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d documentChunkDo) Where(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d documentChunkDo) Order(conds ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d documentChunkDo) Distinct(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d documentChunkDo) Omit(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d documentChunkDo) Join(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d documentChunkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d documentChunkDo) RightJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d documentChunkDo) Group(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d documentChunkDo) Having(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d documentChunkDo) Limit(limit int) IDocumentChunkDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d documentChunkDo) Offset(offset int) IDocumentChunkDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d documentChunkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentChunkDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d documentChunkDo) Unscoped() IDocumentChunkDo {
	return d.withDO(d.DO.Unscoped())
}

func (d documentChunkDo) Create(values ...*entity.DocumentChunk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d documentChunkDo) CreateInBatches(values []*entity.DocumentChunk, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d documentChunkDo) Save(values ...*entity.DocumentChunk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d documentChunkDo) First() (*entity.DocumentChunk, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DocumentChunk), nil
	}
}

func (d documentChunkDo) Take() (*entity.DocumentChunk, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DocumentChunk), nil
	}
}

func (d documentChunkDo) Last() (*entity.DocumentChunk, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DocumentChunk), nil
	}
}

func (d documentChunkDo) Find() ([]*entity.DocumentChunk, error) {
	result, err := d.DO.Find()
	return result.([]*entity.DocumentChunk), err
}

func (d documentChunkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.DocumentChunk, err error) {
	buf := make([]*entity.DocumentChunk, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d documentChunkDo) FindInBatches(result *[]*entity.DocumentChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d documentChunkDo) Attrs(attrs ...field.AssignExpr) IDocumentChunkDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d documentChunkDo) Assign(attrs ...field.AssignExpr) IDocumentChunkDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d documentChunkDo) Joins(fields ...field.RelationField) IDocumentChunkDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d documentChunkDo) Preload(fields ...field.RelationField) IDocumentChunkDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d documentChunkDo) FirstOrInit() (*entity.DocumentChunk, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DocumentChunk), nil
	}
}

func (d documentChunkDo) FirstOrCreate() (*entity.DocumentChunk, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.DocumentChunk), nil
	}
}

func (d documentChunkDo) FindByPage(offset int, limit int) (result []*entity.DocumentChunk, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d documentChunkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d documentChunkDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d documentChunkDo) Delete(models ...*entity.DocumentChunk) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *documentChunkDo) withDO(do gen.Dao) *documentChunkDo {
	d.DO = *do.(*gen.DO)
	return d
}
