// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newEmbedding(db *gorm.DB, opts ...gen.DOOption) embedding {
	_embedding := embedding{}

	_embedding.embeddingDo.UseDB(db, opts...)
	_embedding.embeddingDo.UseModel(&entity.Embedding{})

	tableName := _embedding.embeddingDo.TableName()
	_embedding.ALL = field.NewAsterisk(tableName)
	_embedding.Id = field.NewUint(tableName, "id")
	_embedding.CreatedAt = field.NewTime(tableName, "created_at")
	_embedding.UpdatedAt = field.NewTime(tableName, "updated_at")
	_embedding.Text = field.NewString(tableName, "text")
	_embedding.FileId = field.NewUint(tableName, "file_id")
	_embedding.TextMd5 = field.NewString(tableName, "text_md5")
	_embedding.EmbeddingModel = field.NewString(tableName, "model")
	_embedding.Vector = field.NewField(tableName, "vector")
	_embedding.File = embeddingBelongsToFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("File", "entity.File"),
	}

	_embedding.fillFieldMap()

	return _embedding
}

type embedding struct {
	embeddingDo

	ALL            field.Asterisk
	Id             field.Uint
	CreatedAt      field.Time
	UpdatedAt      field.Time
	Text           field.String
	FileId         field.Uint
	TextMd5        field.String
	EmbeddingModel field.String
	Vector         field.Field
	File           embeddingBelongsToFile

	fieldMap map[string]field.Expr
}

func (e embedding) Table(newTableName string) *embedding {
	e.embeddingDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e embedding) As(alias string) *embedding {
	e.embeddingDo.DO = *(e.embeddingDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *embedding) updateTableName(table string) *embedding {
	e.ALL = field.NewAsterisk(table)
	e.Id = field.NewUint(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.Text = field.NewString(table, "text")
	e.FileId = field.NewUint(table, "file_id")
	e.TextMd5 = field.NewString(table, "text_md5")
	e.EmbeddingModel = field.NewString(table, "model")
	e.Vector = field.NewField(table, "vector")

	e.fillFieldMap()

	return e
}

func (e *embedding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *embedding) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.Id
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["text"] = e.Text
	e.fieldMap["file_id"] = e.FileId
	e.fieldMap["text_md5"] = e.TextMd5
	e.fieldMap["model"] = e.EmbeddingModel
	e.fieldMap["vector"] = e.Vector

}

func (e embedding) clone(db *gorm.DB) embedding {
	e.embeddingDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e embedding) replaceDB(db *gorm.DB) embedding {
	e.embeddingDo.ReplaceDB(db)
	return e
}

type embeddingBelongsToFile struct {
	db *gorm.DB

	field.RelationField
}

func (a embeddingBelongsToFile) Where(conds ...field.Expr) *embeddingBelongsToFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a embeddingBelongsToFile) WithContext(ctx context.Context) *embeddingBelongsToFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a embeddingBelongsToFile) Session(session *gorm.Session) *embeddingBelongsToFile {
	a.db = a.db.Session(session)
	return &a
}

func (a embeddingBelongsToFile) Model(m *entity.Embedding) *embeddingBelongsToFileTx {
	return &embeddingBelongsToFileTx{a.db.Model(m).Association(a.Name())}
}

type embeddingBelongsToFileTx struct{ tx *gorm.Association }

func (a embeddingBelongsToFileTx) Find() (result *entity.File, err error) {
	return result, a.tx.Find(&result)
}

func (a embeddingBelongsToFileTx) Append(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a embeddingBelongsToFileTx) Replace(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a embeddingBelongsToFileTx) Delete(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a embeddingBelongsToFileTx) Clear() error {
	return a.tx.Clear()
}

func (a embeddingBelongsToFileTx) Count() int64 {
	return a.tx.Count()
}

type embeddingDo struct{ gen.DO }

type IEmbeddingDo interface {
	gen.SubQuery
	Debug() IEmbeddingDo
	WithContext(ctx context.Context) IEmbeddingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmbeddingDo
	WriteDB() IEmbeddingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmbeddingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmbeddingDo
	Not(conds ...gen.Condition) IEmbeddingDo
	Or(conds ...gen.Condition) IEmbeddingDo
	Select(conds ...field.Expr) IEmbeddingDo
	Where(conds ...gen.Condition) IEmbeddingDo
	Order(conds ...field.Expr) IEmbeddingDo
	Distinct(cols ...field.Expr) IEmbeddingDo
	Omit(cols ...field.Expr) IEmbeddingDo
	Join(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	Group(cols ...field.Expr) IEmbeddingDo
	Having(conds ...gen.Condition) IEmbeddingDo
	Limit(limit int) IEmbeddingDo
	Offset(offset int) IEmbeddingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmbeddingDo
	Unscoped() IEmbeddingDo
	Create(values ...*entity.Embedding) error
	CreateInBatches(values []*entity.Embedding, batchSize int) error
	Save(values ...*entity.Embedding) error
	First() (*entity.Embedding, error)
	Take() (*entity.Embedding, error)
	Last() (*entity.Embedding, error)
	Find() ([]*entity.Embedding, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Embedding, err error)
	FindInBatches(result *[]*entity.Embedding, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Embedding) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmbeddingDo
	Assign(attrs ...field.AssignExpr) IEmbeddingDo
	Joins(fields ...field.RelationField) IEmbeddingDo
	Preload(fields ...field.RelationField) IEmbeddingDo
	FirstOrInit() (*entity.Embedding, error)
	FirstOrCreate() (*entity.Embedding, error)
	FindByPage(offset int, limit int) (result []*entity.Embedding, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmbeddingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e embeddingDo) Debug() IEmbeddingDo {
	return e.withDO(e.DO.Debug())
}

func (e embeddingDo) WithContext(ctx context.Context) IEmbeddingDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e embeddingDo) ReadDB() IEmbeddingDo {
	return e.Clauses(dbresolver.Read)
}

func (e embeddingDo) WriteDB() IEmbeddingDo {
	return e.Clauses(dbresolver.Write)
}

func (e embeddingDo) Session(config *gorm.Session) IEmbeddingDo {
	return e.withDO(e.DO.Session(config))
}

func (e embeddingDo) Clauses(conds ...clause.Expression) IEmbeddingDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e embeddingDo) Returning(value interface{}, columns ...string) IEmbeddingDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e embeddingDo) Not(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e embeddingDo) Or(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e embeddingDo) Select(conds ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e embeddingDo) Where(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e embeddingDo) Order(conds ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e embeddingDo) Distinct(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e embeddingDo) Omit(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e embeddingDo) Join(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e embeddingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e embeddingDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e embeddingDo) Group(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e embeddingDo) Having(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e embeddingDo) Limit(limit int) IEmbeddingDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e embeddingDo) Offset(offset int) IEmbeddingDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e embeddingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmbeddingDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e embeddingDo) Unscoped() IEmbeddingDo {
	return e.withDO(e.DO.Unscoped())
}

func (e embeddingDo) Create(values ...*entity.Embedding) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e embeddingDo) CreateInBatches(values []*entity.Embedding, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e embeddingDo) Save(values ...*entity.Embedding) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e embeddingDo) First() (*entity.Embedding, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Embedding), nil
	}
}

func (e embeddingDo) Take() (*entity.Embedding, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Embedding), nil
	}
}

func (e embeddingDo) Last() (*entity.Embedding, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Embedding), nil
	}
}

func (e embeddingDo) Find() ([]*entity.Embedding, error) {
	result, err := e.DO.Find()
	return result.([]*entity.Embedding), err
}

func (e embeddingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Embedding, err error) {
	buf := make([]*entity.Embedding, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e embeddingDo) FindInBatches(result *[]*entity.Embedding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e embeddingDo) Attrs(attrs ...field.AssignExpr) IEmbeddingDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e embeddingDo) Assign(attrs ...field.AssignExpr) IEmbeddingDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e embeddingDo) Joins(fields ...field.RelationField) IEmbeddingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e embeddingDo) Preload(fields ...field.RelationField) IEmbeddingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e embeddingDo) FirstOrInit() (*entity.Embedding, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Embedding), nil
	}
}

func (e embeddingDo) FirstOrCreate() (*entity.Embedding, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Embedding), nil
	}
}

func (e embeddingDo) FindByPage(offset int, limit int) (result []*entity.Embedding, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e embeddingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e embeddingDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e embeddingDo) Delete(models ...*entity.Embedding) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *embeddingDo) withDO(do gen.Dao) *embeddingDo {
	e.DO = *do.(*gen.DO)
	return e
}
