// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newFavoriteAssistants(db *gorm.DB, opts ...gen.DOOption) favoriteAssistants {
	_favoriteAssistants := favoriteAssistants{}

	_favoriteAssistants.favoriteAssistantsDo.UseDB(db, opts...)
	_favoriteAssistants.favoriteAssistantsDo.UseModel(&entity.FavoriteAssistants{})

	tableName := _favoriteAssistants.favoriteAssistantsDo.TableName()
	_favoriteAssistants.ALL = field.NewAsterisk(tableName)
	_favoriteAssistants.Id = field.NewUint(tableName, "id")
	_favoriteAssistants.CreatedAt = field.NewTime(tableName, "created_at")
	_favoriteAssistants.UpdatedAt = field.NewTime(tableName, "updated_at")
	_favoriteAssistants.AssistantId = field.NewUint(tableName, "assistant_id")
	_favoriteAssistants.UserId = field.NewString(tableName, "user_id")
	_favoriteAssistants.Deleted = field.NewBool(tableName, "deleted")
	_favoriteAssistants.Assistant = favoriteAssistantsBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_favoriteAssistants.fillFieldMap()

	return _favoriteAssistants
}

type favoriteAssistants struct {
	favoriteAssistantsDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	AssistantId field.Uint
	UserId      field.String
	Deleted     field.Bool
	Assistant   favoriteAssistantsBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (f favoriteAssistants) Table(newTableName string) *favoriteAssistants {
	f.favoriteAssistantsDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f favoriteAssistants) As(alias string) *favoriteAssistants {
	f.favoriteAssistantsDo.DO = *(f.favoriteAssistantsDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *favoriteAssistants) updateTableName(table string) *favoriteAssistants {
	f.ALL = field.NewAsterisk(table)
	f.Id = field.NewUint(table, "id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.AssistantId = field.NewUint(table, "assistant_id")
	f.UserId = field.NewString(table, "user_id")
	f.Deleted = field.NewBool(table, "deleted")

	f.fillFieldMap()

	return f
}

func (f *favoriteAssistants) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *favoriteAssistants) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.Id
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["assistant_id"] = f.AssistantId
	f.fieldMap["user_id"] = f.UserId
	f.fieldMap["deleted"] = f.Deleted

}

func (f favoriteAssistants) clone(db *gorm.DB) favoriteAssistants {
	f.favoriteAssistantsDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f favoriteAssistants) replaceDB(db *gorm.DB) favoriteAssistants {
	f.favoriteAssistantsDo.ReplaceDB(db)
	return f
}

type favoriteAssistantsBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a favoriteAssistantsBelongsToAssistant) Where(conds ...field.Expr) *favoriteAssistantsBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a favoriteAssistantsBelongsToAssistant) WithContext(ctx context.Context) *favoriteAssistantsBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a favoriteAssistantsBelongsToAssistant) Session(session *gorm.Session) *favoriteAssistantsBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a favoriteAssistantsBelongsToAssistant) Model(m *entity.FavoriteAssistants) *favoriteAssistantsBelongsToAssistantTx {
	return &favoriteAssistantsBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type favoriteAssistantsBelongsToAssistantTx struct{ tx *gorm.Association }

func (a favoriteAssistantsBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a favoriteAssistantsBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a favoriteAssistantsBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a favoriteAssistantsBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a favoriteAssistantsBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a favoriteAssistantsBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type favoriteAssistantsDo struct{ gen.DO }

type IFavoriteAssistantsDo interface {
	gen.SubQuery
	Debug() IFavoriteAssistantsDo
	WithContext(ctx context.Context) IFavoriteAssistantsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFavoriteAssistantsDo
	WriteDB() IFavoriteAssistantsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFavoriteAssistantsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFavoriteAssistantsDo
	Not(conds ...gen.Condition) IFavoriteAssistantsDo
	Or(conds ...gen.Condition) IFavoriteAssistantsDo
	Select(conds ...field.Expr) IFavoriteAssistantsDo
	Where(conds ...gen.Condition) IFavoriteAssistantsDo
	Order(conds ...field.Expr) IFavoriteAssistantsDo
	Distinct(cols ...field.Expr) IFavoriteAssistantsDo
	Omit(cols ...field.Expr) IFavoriteAssistantsDo
	Join(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo
	Group(cols ...field.Expr) IFavoriteAssistantsDo
	Having(conds ...gen.Condition) IFavoriteAssistantsDo
	Limit(limit int) IFavoriteAssistantsDo
	Offset(offset int) IFavoriteAssistantsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFavoriteAssistantsDo
	Unscoped() IFavoriteAssistantsDo
	Create(values ...*entity.FavoriteAssistants) error
	CreateInBatches(values []*entity.FavoriteAssistants, batchSize int) error
	Save(values ...*entity.FavoriteAssistants) error
	First() (*entity.FavoriteAssistants, error)
	Take() (*entity.FavoriteAssistants, error)
	Last() (*entity.FavoriteAssistants, error)
	Find() ([]*entity.FavoriteAssistants, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FavoriteAssistants, err error)
	FindInBatches(result *[]*entity.FavoriteAssistants, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.FavoriteAssistants) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFavoriteAssistantsDo
	Assign(attrs ...field.AssignExpr) IFavoriteAssistantsDo
	Joins(fields ...field.RelationField) IFavoriteAssistantsDo
	Preload(fields ...field.RelationField) IFavoriteAssistantsDo
	FirstOrInit() (*entity.FavoriteAssistants, error)
	FirstOrCreate() (*entity.FavoriteAssistants, error)
	FindByPage(offset int, limit int) (result []*entity.FavoriteAssistants, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFavoriteAssistantsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f favoriteAssistantsDo) Debug() IFavoriteAssistantsDo {
	return f.withDO(f.DO.Debug())
}

func (f favoriteAssistantsDo) WithContext(ctx context.Context) IFavoriteAssistantsDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f favoriteAssistantsDo) ReadDB() IFavoriteAssistantsDo {
	return f.Clauses(dbresolver.Read)
}

func (f favoriteAssistantsDo) WriteDB() IFavoriteAssistantsDo {
	return f.Clauses(dbresolver.Write)
}

func (f favoriteAssistantsDo) Session(config *gorm.Session) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Session(config))
}

func (f favoriteAssistantsDo) Clauses(conds ...clause.Expression) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f favoriteAssistantsDo) Returning(value interface{}, columns ...string) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f favoriteAssistantsDo) Not(conds ...gen.Condition) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f favoriteAssistantsDo) Or(conds ...gen.Condition) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f favoriteAssistantsDo) Select(conds ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f favoriteAssistantsDo) Where(conds ...gen.Condition) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f favoriteAssistantsDo) Order(conds ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f favoriteAssistantsDo) Distinct(cols ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f favoriteAssistantsDo) Omit(cols ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f favoriteAssistantsDo) Join(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f favoriteAssistantsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f favoriteAssistantsDo) RightJoin(table schema.Tabler, on ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f favoriteAssistantsDo) Group(cols ...field.Expr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f favoriteAssistantsDo) Having(conds ...gen.Condition) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f favoriteAssistantsDo) Limit(limit int) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f favoriteAssistantsDo) Offset(offset int) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f favoriteAssistantsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f favoriteAssistantsDo) Unscoped() IFavoriteAssistantsDo {
	return f.withDO(f.DO.Unscoped())
}

func (f favoriteAssistantsDo) Create(values ...*entity.FavoriteAssistants) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f favoriteAssistantsDo) CreateInBatches(values []*entity.FavoriteAssistants, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f favoriteAssistantsDo) Save(values ...*entity.FavoriteAssistants) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f favoriteAssistantsDo) First() (*entity.FavoriteAssistants, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FavoriteAssistants), nil
	}
}

func (f favoriteAssistantsDo) Take() (*entity.FavoriteAssistants, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FavoriteAssistants), nil
	}
}

func (f favoriteAssistantsDo) Last() (*entity.FavoriteAssistants, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FavoriteAssistants), nil
	}
}

func (f favoriteAssistantsDo) Find() ([]*entity.FavoriteAssistants, error) {
	result, err := f.DO.Find()
	return result.([]*entity.FavoriteAssistants), err
}

func (f favoriteAssistantsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.FavoriteAssistants, err error) {
	buf := make([]*entity.FavoriteAssistants, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f favoriteAssistantsDo) FindInBatches(result *[]*entity.FavoriteAssistants, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f favoriteAssistantsDo) Attrs(attrs ...field.AssignExpr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f favoriteAssistantsDo) Assign(attrs ...field.AssignExpr) IFavoriteAssistantsDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f favoriteAssistantsDo) Joins(fields ...field.RelationField) IFavoriteAssistantsDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f favoriteAssistantsDo) Preload(fields ...field.RelationField) IFavoriteAssistantsDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f favoriteAssistantsDo) FirstOrInit() (*entity.FavoriteAssistants, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FavoriteAssistants), nil
	}
}

func (f favoriteAssistantsDo) FirstOrCreate() (*entity.FavoriteAssistants, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.FavoriteAssistants), nil
	}
}

func (f favoriteAssistantsDo) FindByPage(offset int, limit int) (result []*entity.FavoriteAssistants, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f favoriteAssistantsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f favoriteAssistantsDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f favoriteAssistantsDo) Delete(models ...*entity.FavoriteAssistants) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *favoriteAssistantsDo) withDO(do gen.Dao) *favoriteAssistantsDo {
	f.DO = *do.(*gen.DO)
	return f
}
