// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	Assistant          *assistant
	AssistantKey       *assistantKey
	AssistantTool      *assistantTool
	Chat               *chat
	ChatMessage        *chatMessage
	Document           *document
	DocumentChunk      *documentChunk
	Embedding          *embedding
	FavoriteAssistants *favoriteAssistants
	File               *file
	Library            *library
	Memory             *memory
	MessageBlock       *messageBlock
	Tool               *tool
	ToolCallToken      *toolCallToken
	UnsettledToken     *unsettledToken
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Assistant = &Q.Assistant
	AssistantKey = &Q.AssistantKey
	AssistantTool = &Q.AssistantTool
	Chat = &Q.Chat
	ChatMessage = &Q.ChatMessage
	Document = &Q.Document
	DocumentChunk = &Q.DocumentChunk
	Embedding = &Q.Embedding
	FavoriteAssistants = &Q.FavoriteAssistants
	File = &Q.File
	Library = &Q.Library
	Memory = &Q.Memory
	MessageBlock = &Q.MessageBlock
	Tool = &Q.Tool
	ToolCallToken = &Q.ToolCallToken
	UnsettledToken = &Q.UnsettledToken
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Assistant:          newAssistant(db, opts...),
		AssistantKey:       newAssistantKey(db, opts...),
		AssistantTool:      newAssistantTool(db, opts...),
		Chat:               newChat(db, opts...),
		ChatMessage:        newChatMessage(db, opts...),
		Document:           newDocument(db, opts...),
		DocumentChunk:      newDocumentChunk(db, opts...),
		Embedding:          newEmbedding(db, opts...),
		FavoriteAssistants: newFavoriteAssistants(db, opts...),
		File:               newFile(db, opts...),
		Library:            newLibrary(db, opts...),
		Memory:             newMemory(db, opts...),
		MessageBlock:       newMessageBlock(db, opts...),
		Tool:               newTool(db, opts...),
		ToolCallToken:      newToolCallToken(db, opts...),
		UnsettledToken:     newUnsettledToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Assistant          assistant
	AssistantKey       assistantKey
	AssistantTool      assistantTool
	Chat               chat
	ChatMessage        chatMessage
	Document           document
	DocumentChunk      documentChunk
	Embedding          embedding
	FavoriteAssistants favoriteAssistants
	File               file
	Library            library
	Memory             memory
	MessageBlock       messageBlock
	Tool               tool
	ToolCallToken      toolCallToken
	UnsettledToken     unsettledToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Assistant:          q.Assistant.clone(db),
		AssistantKey:       q.AssistantKey.clone(db),
		AssistantTool:      q.AssistantTool.clone(db),
		Chat:               q.Chat.clone(db),
		ChatMessage:        q.ChatMessage.clone(db),
		Document:           q.Document.clone(db),
		DocumentChunk:      q.DocumentChunk.clone(db),
		Embedding:          q.Embedding.clone(db),
		FavoriteAssistants: q.FavoriteAssistants.clone(db),
		File:               q.File.clone(db),
		Library:            q.Library.clone(db),
		Memory:             q.Memory.clone(db),
		MessageBlock:       q.MessageBlock.clone(db),
		Tool:               q.Tool.clone(db),
		ToolCallToken:      q.ToolCallToken.clone(db),
		UnsettledToken:     q.UnsettledToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Assistant:          q.Assistant.replaceDB(db),
		AssistantKey:       q.AssistantKey.replaceDB(db),
		AssistantTool:      q.AssistantTool.replaceDB(db),
		Chat:               q.Chat.replaceDB(db),
		ChatMessage:        q.ChatMessage.replaceDB(db),
		Document:           q.Document.replaceDB(db),
		DocumentChunk:      q.DocumentChunk.replaceDB(db),
		Embedding:          q.Embedding.replaceDB(db),
		FavoriteAssistants: q.FavoriteAssistants.replaceDB(db),
		File:               q.File.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		Memory:             q.Memory.replaceDB(db),
		MessageBlock:       q.MessageBlock.replaceDB(db),
		Tool:               q.Tool.replaceDB(db),
		ToolCallToken:      q.ToolCallToken.replaceDB(db),
		UnsettledToken:     q.UnsettledToken.replaceDB(db),
	}
}

type queryCtx struct {
	Assistant          IAssistantDo
	AssistantKey       IAssistantKeyDo
	AssistantTool      IAssistantToolDo
	Chat               IChatDo
	ChatMessage        IChatMessageDo
	Document           IDocumentDo
	DocumentChunk      IDocumentChunkDo
	Embedding          IEmbeddingDo
	FavoriteAssistants IFavoriteAssistantsDo
	File               IFileDo
	Library            ILibraryDo
	Memory             IMemoryDo
	MessageBlock       IMessageBlockDo
	Tool               IToolDo
	ToolCallToken      IToolCallTokenDo
	UnsettledToken     IUnsettledTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Assistant:          q.Assistant.WithContext(ctx),
		AssistantKey:       q.AssistantKey.WithContext(ctx),
		AssistantTool:      q.AssistantTool.WithContext(ctx),
		Chat:               q.Chat.WithContext(ctx),
		ChatMessage:        q.ChatMessage.WithContext(ctx),
		Document:           q.Document.WithContext(ctx),
		DocumentChunk:      q.DocumentChunk.WithContext(ctx),
		Embedding:          q.Embedding.WithContext(ctx),
		FavoriteAssistants: q.FavoriteAssistants.WithContext(ctx),
		File:               q.File.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		Memory:             q.Memory.WithContext(ctx),
		MessageBlock:       q.MessageBlock.WithContext(ctx),
		Tool:               q.Tool.WithContext(ctx),
		ToolCallToken:      q.ToolCallToken.WithContext(ctx),
		UnsettledToken:     q.UnsettledToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
