// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Assistant      *assistant
	AssistantShare *assistantShare
	Chat           *chat
	File           *file
	Tool           *tool
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Assistant = &Q.Assistant
	AssistantShare = &Q.AssistantShare
	Chat = &Q.Chat
	File = &Q.File
	Tool = &Q.Tool
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Assistant:      newAssistant(db, opts...),
		AssistantShare: newAssistantShare(db, opts...),
		Chat:           newChat(db, opts...),
		File:           newFile(db, opts...),
		Tool:           newTool(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Assistant      assistant
	AssistantShare assistantShare
	Chat           chat
	File           file
	Tool           tool
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Assistant:      q.Assistant.clone(db),
		AssistantShare: q.AssistantShare.clone(db),
		Chat:           q.Chat.clone(db),
		File:           q.File.clone(db),
		Tool:           q.Tool.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Assistant:      q.Assistant.replaceDB(db),
		AssistantShare: q.AssistantShare.replaceDB(db),
		Chat:           q.Chat.replaceDB(db),
		File:           q.File.replaceDB(db),
		Tool:           q.Tool.replaceDB(db),
	}
}

type queryCtx struct {
	Assistant      IAssistantDo
	AssistantShare IAssistantShareDo
	Chat           IChatDo
	File           IFileDo
	Tool           IToolDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Assistant:      q.Assistant.WithContext(ctx),
		AssistantShare: q.AssistantShare.WithContext(ctx),
		Chat:           q.Chat.WithContext(ctx),
		File:           q.File.WithContext(ctx),
		Tool:           q.Tool.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
