// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newLibrary(db *gorm.DB, opts ...gen.DOOption) library {
	_library := library{}

	_library.libraryDo.UseDB(db, opts...)
	_library.libraryDo.UseModel(&entity.Library{})

	tableName := _library.libraryDo.TableName()
	_library.ALL = field.NewAsterisk(tableName)
	_library.Id = field.NewUint(tableName, "id")
	_library.CreatedAt = field.NewTime(tableName, "created_at")
	_library.UpdatedAt = field.NewTime(tableName, "updated_at")
	_library.Name = field.NewString(tableName, "name")
	_library.Default = field.NewBool(tableName, "default")
	_library.Description = field.NewString(tableName, "description")
	_library.UserId = field.NewInt64(tableName, "user_id")
	_library.Document = libraryHasManyDocument{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Document", "entity.Document"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Document.Library", "entity.Library"),
			Document: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Document.Library.Document", "entity.Document"),
			},
		},
		File: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Document.File", "entity.File"),
		},
	}

	_library.fillFieldMap()

	return _library
}

type library struct {
	libraryDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Name        field.String
	Default     field.Bool
	Description field.String
	UserId      field.Int64
	Document    libraryHasManyDocument

	fieldMap map[string]field.Expr
}

func (l library) Table(newTableName string) *library {
	l.libraryDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l library) As(alias string) *library {
	l.libraryDo.DO = *(l.libraryDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *library) updateTableName(table string) *library {
	l.ALL = field.NewAsterisk(table)
	l.Id = field.NewUint(table, "id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.Name = field.NewString(table, "name")
	l.Default = field.NewBool(table, "default")
	l.Description = field.NewString(table, "description")
	l.UserId = field.NewInt64(table, "user_id")

	l.fillFieldMap()

	return l
}

func (l *library) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *library) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 8)
	l.fieldMap["id"] = l.Id
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["name"] = l.Name
	l.fieldMap["default"] = l.Default
	l.fieldMap["description"] = l.Description
	l.fieldMap["user_id"] = l.UserId

}

func (l library) clone(db *gorm.DB) library {
	l.libraryDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l library) replaceDB(db *gorm.DB) library {
	l.libraryDo.ReplaceDB(db)
	return l
}

type libraryHasManyDocument struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
		}
	}
	File struct {
		field.RelationField
	}
}

func (a libraryHasManyDocument) Where(conds ...field.Expr) *libraryHasManyDocument {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a libraryHasManyDocument) WithContext(ctx context.Context) *libraryHasManyDocument {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a libraryHasManyDocument) Session(session *gorm.Session) *libraryHasManyDocument {
	a.db = a.db.Session(session)
	return &a
}

func (a libraryHasManyDocument) Model(m *entity.Library) *libraryHasManyDocumentTx {
	return &libraryHasManyDocumentTx{a.db.Model(m).Association(a.Name())}
}

type libraryHasManyDocumentTx struct{ tx *gorm.Association }

func (a libraryHasManyDocumentTx) Find() (result []*entity.Document, err error) {
	return result, a.tx.Find(&result)
}

func (a libraryHasManyDocumentTx) Append(values ...*entity.Document) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a libraryHasManyDocumentTx) Replace(values ...*entity.Document) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a libraryHasManyDocumentTx) Delete(values ...*entity.Document) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a libraryHasManyDocumentTx) Clear() error {
	return a.tx.Clear()
}

func (a libraryHasManyDocumentTx) Count() int64 {
	return a.tx.Count()
}

type libraryDo struct{ gen.DO }

type ILibraryDo interface {
	gen.SubQuery
	Debug() ILibraryDo
	WithContext(ctx context.Context) ILibraryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILibraryDo
	WriteDB() ILibraryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILibraryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILibraryDo
	Not(conds ...gen.Condition) ILibraryDo
	Or(conds ...gen.Condition) ILibraryDo
	Select(conds ...field.Expr) ILibraryDo
	Where(conds ...gen.Condition) ILibraryDo
	Order(conds ...field.Expr) ILibraryDo
	Distinct(cols ...field.Expr) ILibraryDo
	Omit(cols ...field.Expr) ILibraryDo
	Join(table schema.Tabler, on ...field.Expr) ILibraryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILibraryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILibraryDo
	Group(cols ...field.Expr) ILibraryDo
	Having(conds ...gen.Condition) ILibraryDo
	Limit(limit int) ILibraryDo
	Offset(offset int) ILibraryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILibraryDo
	Unscoped() ILibraryDo
	Create(values ...*entity.Library) error
	CreateInBatches(values []*entity.Library, batchSize int) error
	Save(values ...*entity.Library) error
	First() (*entity.Library, error)
	Take() (*entity.Library, error)
	Last() (*entity.Library, error)
	Find() ([]*entity.Library, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Library, err error)
	FindInBatches(result *[]*entity.Library, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Library) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILibraryDo
	Assign(attrs ...field.AssignExpr) ILibraryDo
	Joins(fields ...field.RelationField) ILibraryDo
	Preload(fields ...field.RelationField) ILibraryDo
	FirstOrInit() (*entity.Library, error)
	FirstOrCreate() (*entity.Library, error)
	FindByPage(offset int, limit int) (result []*entity.Library, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILibraryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l libraryDo) Debug() ILibraryDo {
	return l.withDO(l.DO.Debug())
}

func (l libraryDo) WithContext(ctx context.Context) ILibraryDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l libraryDo) ReadDB() ILibraryDo {
	return l.Clauses(dbresolver.Read)
}

func (l libraryDo) WriteDB() ILibraryDo {
	return l.Clauses(dbresolver.Write)
}

func (l libraryDo) Session(config *gorm.Session) ILibraryDo {
	return l.withDO(l.DO.Session(config))
}

func (l libraryDo) Clauses(conds ...clause.Expression) ILibraryDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l libraryDo) Returning(value interface{}, columns ...string) ILibraryDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l libraryDo) Not(conds ...gen.Condition) ILibraryDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l libraryDo) Or(conds ...gen.Condition) ILibraryDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l libraryDo) Select(conds ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l libraryDo) Where(conds ...gen.Condition) ILibraryDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l libraryDo) Order(conds ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l libraryDo) Distinct(cols ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l libraryDo) Omit(cols ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l libraryDo) Join(table schema.Tabler, on ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l libraryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l libraryDo) RightJoin(table schema.Tabler, on ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l libraryDo) Group(cols ...field.Expr) ILibraryDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l libraryDo) Having(conds ...gen.Condition) ILibraryDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l libraryDo) Limit(limit int) ILibraryDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l libraryDo) Offset(offset int) ILibraryDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l libraryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILibraryDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l libraryDo) Unscoped() ILibraryDo {
	return l.withDO(l.DO.Unscoped())
}

func (l libraryDo) Create(values ...*entity.Library) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l libraryDo) CreateInBatches(values []*entity.Library, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l libraryDo) Save(values ...*entity.Library) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l libraryDo) First() (*entity.Library, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Library), nil
	}
}

func (l libraryDo) Take() (*entity.Library, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Library), nil
	}
}

func (l libraryDo) Last() (*entity.Library, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Library), nil
	}
}

func (l libraryDo) Find() ([]*entity.Library, error) {
	result, err := l.DO.Find()
	return result.([]*entity.Library), err
}

func (l libraryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Library, err error) {
	buf := make([]*entity.Library, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l libraryDo) FindInBatches(result *[]*entity.Library, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l libraryDo) Attrs(attrs ...field.AssignExpr) ILibraryDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l libraryDo) Assign(attrs ...field.AssignExpr) ILibraryDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l libraryDo) Joins(fields ...field.RelationField) ILibraryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l libraryDo) Preload(fields ...field.RelationField) ILibraryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l libraryDo) FirstOrInit() (*entity.Library, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Library), nil
	}
}

func (l libraryDo) FirstOrCreate() (*entity.Library, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Library), nil
	}
}

func (l libraryDo) FindByPage(offset int, limit int) (result []*entity.Library, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l libraryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l libraryDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l libraryDo) Delete(models ...*entity.Library) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *libraryDo) withDO(do gen.Dao) *libraryDo {
	l.DO = *do.(*gen.DO)
	return l
}
