// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newMessageBlock(db *gorm.DB, opts ...gen.DOOption) messageBlock {
	_messageBlock := messageBlock{}

	_messageBlock.messageBlockDo.UseDB(db, opts...)
	_messageBlock.messageBlockDo.UseModel(&entity.MessageBlock{})

	tableName := _messageBlock.messageBlockDo.TableName()
	_messageBlock.ALL = field.NewAsterisk(tableName)
	_messageBlock.Id = field.NewUint(tableName, "id")
	_messageBlock.CreatedAt = field.NewTime(tableName, "created_at")
	_messageBlock.UpdatedAt = field.NewTime(tableName, "updated_at")
	_messageBlock.FullContent = field.NewString(tableName, "full_content")
	_messageBlock.ChatId = field.NewUint(tableName, "chat_id")
	_messageBlock.Hash = field.NewString(tableName, "hash")
	_messageBlock.Message = field.NewField(tableName, "messages")

	_messageBlock.fillFieldMap()

	return _messageBlock
}

type messageBlock struct {
	messageBlockDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	FullContent field.String
	ChatId      field.Uint
	Hash        field.String
	Message     field.Field

	fieldMap map[string]field.Expr
}

func (m messageBlock) Table(newTableName string) *messageBlock {
	m.messageBlockDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m messageBlock) As(alias string) *messageBlock {
	m.messageBlockDo.DO = *(m.messageBlockDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *messageBlock) updateTableName(table string) *messageBlock {
	m.ALL = field.NewAsterisk(table)
	m.Id = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.FullContent = field.NewString(table, "full_content")
	m.ChatId = field.NewUint(table, "chat_id")
	m.Hash = field.NewString(table, "hash")
	m.Message = field.NewField(table, "messages")

	m.fillFieldMap()

	return m
}

func (m *messageBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *messageBlock) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.Id
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["full_content"] = m.FullContent
	m.fieldMap["chat_id"] = m.ChatId
	m.fieldMap["hash"] = m.Hash
	m.fieldMap["messages"] = m.Message
}

func (m messageBlock) clone(db *gorm.DB) messageBlock {
	m.messageBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m messageBlock) replaceDB(db *gorm.DB) messageBlock {
	m.messageBlockDo.ReplaceDB(db)
	return m
}

type messageBlockDo struct{ gen.DO }

type IMessageBlockDo interface {
	gen.SubQuery
	Debug() IMessageBlockDo
	WithContext(ctx context.Context) IMessageBlockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMessageBlockDo
	WriteDB() IMessageBlockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMessageBlockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMessageBlockDo
	Not(conds ...gen.Condition) IMessageBlockDo
	Or(conds ...gen.Condition) IMessageBlockDo
	Select(conds ...field.Expr) IMessageBlockDo
	Where(conds ...gen.Condition) IMessageBlockDo
	Order(conds ...field.Expr) IMessageBlockDo
	Distinct(cols ...field.Expr) IMessageBlockDo
	Omit(cols ...field.Expr) IMessageBlockDo
	Join(table schema.Tabler, on ...field.Expr) IMessageBlockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMessageBlockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMessageBlockDo
	Group(cols ...field.Expr) IMessageBlockDo
	Having(conds ...gen.Condition) IMessageBlockDo
	Limit(limit int) IMessageBlockDo
	Offset(offset int) IMessageBlockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageBlockDo
	Unscoped() IMessageBlockDo
	Create(values ...*entity.MessageBlock) error
	CreateInBatches(values []*entity.MessageBlock, batchSize int) error
	Save(values ...*entity.MessageBlock) error
	First() (*entity.MessageBlock, error)
	Take() (*entity.MessageBlock, error)
	Last() (*entity.MessageBlock, error)
	Find() ([]*entity.MessageBlock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.MessageBlock, err error)
	FindInBatches(result *[]*entity.MessageBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.MessageBlock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMessageBlockDo
	Assign(attrs ...field.AssignExpr) IMessageBlockDo
	Joins(fields ...field.RelationField) IMessageBlockDo
	Preload(fields ...field.RelationField) IMessageBlockDo
	FirstOrInit() (*entity.MessageBlock, error)
	FirstOrCreate() (*entity.MessageBlock, error)
	FindByPage(offset int, limit int) (result []*entity.MessageBlock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMessageBlockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m messageBlockDo) Debug() IMessageBlockDo {
	return m.withDO(m.DO.Debug())
}

func (m messageBlockDo) WithContext(ctx context.Context) IMessageBlockDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m messageBlockDo) ReadDB() IMessageBlockDo {
	return m.Clauses(dbresolver.Read)
}

func (m messageBlockDo) WriteDB() IMessageBlockDo {
	return m.Clauses(dbresolver.Write)
}

func (m messageBlockDo) Session(config *gorm.Session) IMessageBlockDo {
	return m.withDO(m.DO.Session(config))
}

func (m messageBlockDo) Clauses(conds ...clause.Expression) IMessageBlockDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m messageBlockDo) Returning(value interface{}, columns ...string) IMessageBlockDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m messageBlockDo) Not(conds ...gen.Condition) IMessageBlockDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m messageBlockDo) Or(conds ...gen.Condition) IMessageBlockDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m messageBlockDo) Select(conds ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m messageBlockDo) Where(conds ...gen.Condition) IMessageBlockDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m messageBlockDo) Order(conds ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m messageBlockDo) Distinct(cols ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m messageBlockDo) Omit(cols ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m messageBlockDo) Join(table schema.Tabler, on ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m messageBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m messageBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m messageBlockDo) Group(cols ...field.Expr) IMessageBlockDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m messageBlockDo) Having(conds ...gen.Condition) IMessageBlockDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m messageBlockDo) Limit(limit int) IMessageBlockDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m messageBlockDo) Offset(offset int) IMessageBlockDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m messageBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageBlockDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m messageBlockDo) Unscoped() IMessageBlockDo {
	return m.withDO(m.DO.Unscoped())
}

func (m messageBlockDo) Create(values ...*entity.MessageBlock) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m messageBlockDo) CreateInBatches(values []*entity.MessageBlock, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m messageBlockDo) Save(values ...*entity.MessageBlock) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m messageBlockDo) First() (*entity.MessageBlock, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.MessageBlock), nil
	}
}

func (m messageBlockDo) Take() (*entity.MessageBlock, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.MessageBlock), nil
	}
}

func (m messageBlockDo) Last() (*entity.MessageBlock, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.MessageBlock), nil
	}
}

func (m messageBlockDo) Find() ([]*entity.MessageBlock, error) {
	result, err := m.DO.Find()
	return result.([]*entity.MessageBlock), err
}

func (m messageBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.MessageBlock, err error) {
	buf := make([]*entity.MessageBlock, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m messageBlockDo) FindInBatches(result *[]*entity.MessageBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m messageBlockDo) Attrs(attrs ...field.AssignExpr) IMessageBlockDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m messageBlockDo) Assign(attrs ...field.AssignExpr) IMessageBlockDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m messageBlockDo) Joins(fields ...field.RelationField) IMessageBlockDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m messageBlockDo) Preload(fields ...field.RelationField) IMessageBlockDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m messageBlockDo) FirstOrInit() (*entity.MessageBlock, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.MessageBlock), nil
	}
}

func (m messageBlockDo) FirstOrCreate() (*entity.MessageBlock, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.MessageBlock), nil
	}
}

func (m messageBlockDo) FindByPage(offset int, limit int) (result []*entity.MessageBlock, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m messageBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m messageBlockDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m messageBlockDo) Delete(models ...*entity.MessageBlock) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *messageBlockDo) withDO(do gen.Dao) *messageBlockDo {
	m.DO = *do.(*gen.DO)
	return m
}
