// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newScenePrompt(db *gorm.DB, opts ...gen.DOOption) scenePrompt {
	_scenePrompt := scenePrompt{}

	_scenePrompt.scenePromptDo.UseDB(db, opts...)
	_scenePrompt.scenePromptDo.UseModel(&entity.ScenePrompt{})

	tableName := _scenePrompt.scenePromptDo.TableName()
	_scenePrompt.ALL = field.NewAsterisk(tableName)
	_scenePrompt.Id = field.NewUint(tableName, "id")
	_scenePrompt.CreatedAt = field.NewTime(tableName, "created_at")
	_scenePrompt.UpdatedAt = field.NewTime(tableName, "updated_at")
	_scenePrompt.Label = field.NewString(tableName, "label")
	_scenePrompt.Prompt = field.NewString(tableName, "prompt")
	_scenePrompt.AssistantId = field.NewUint(tableName, "assistant_id")
	_scenePrompt.Assistant = scenePromptBelongsToAssistant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assistant", "entity.Assistant"),
		Library: struct {
			field.RelationField
			Document struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Assistant.Library", "entity.Library"),
			Document: struct {
				field.RelationField
				Library struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Assistant.Library.Document", "entity.Document"),
				Library: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Assistant.Library.Document.Library", "entity.Library"),
				},
			},
		},
	}

	_scenePrompt.fillFieldMap()

	return _scenePrompt
}

type scenePrompt struct {
	scenePromptDo

	ALL         field.Asterisk
	Id          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Label       field.String
	Prompt      field.String
	AssistantId field.Uint
	Assistant   scenePromptBelongsToAssistant

	fieldMap map[string]field.Expr
}

func (s scenePrompt) Table(newTableName string) *scenePrompt {
	s.scenePromptDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scenePrompt) As(alias string) *scenePrompt {
	s.scenePromptDo.DO = *(s.scenePromptDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scenePrompt) updateTableName(table string) *scenePrompt {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.Label = field.NewString(table, "label")
	s.Prompt = field.NewString(table, "prompt")
	s.AssistantId = field.NewUint(table, "assistant_id")

	s.fillFieldMap()

	return s
}

func (s *scenePrompt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scenePrompt) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.Id
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["label"] = s.Label
	s.fieldMap["prompt"] = s.Prompt
	s.fieldMap["assistant_id"] = s.AssistantId

}

func (s scenePrompt) clone(db *gorm.DB) scenePrompt {
	s.scenePromptDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scenePrompt) replaceDB(db *gorm.DB) scenePrompt {
	s.scenePromptDo.ReplaceDB(db)
	return s
}

type scenePromptBelongsToAssistant struct {
	db *gorm.DB

	field.RelationField

	Library struct {
		field.RelationField
		Document struct {
			field.RelationField
			Library struct {
				field.RelationField
			}
		}
	}
}

func (a scenePromptBelongsToAssistant) Where(conds ...field.Expr) *scenePromptBelongsToAssistant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scenePromptBelongsToAssistant) WithContext(ctx context.Context) *scenePromptBelongsToAssistant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scenePromptBelongsToAssistant) Session(session *gorm.Session) *scenePromptBelongsToAssistant {
	a.db = a.db.Session(session)
	return &a
}

func (a scenePromptBelongsToAssistant) Model(m *entity.ScenePrompt) *scenePromptBelongsToAssistantTx {
	return &scenePromptBelongsToAssistantTx{a.db.Model(m).Association(a.Name())}
}

type scenePromptBelongsToAssistantTx struct{ tx *gorm.Association }

func (a scenePromptBelongsToAssistantTx) Find() (result *entity.Assistant, err error) {
	return result, a.tx.Find(&result)
}

func (a scenePromptBelongsToAssistantTx) Append(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scenePromptBelongsToAssistantTx) Replace(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scenePromptBelongsToAssistantTx) Delete(values ...*entity.Assistant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scenePromptBelongsToAssistantTx) Clear() error {
	return a.tx.Clear()
}

func (a scenePromptBelongsToAssistantTx) Count() int64 {
	return a.tx.Count()
}

type scenePromptDo struct{ gen.DO }

type IScenePromptDo interface {
	gen.SubQuery
	Debug() IScenePromptDo
	WithContext(ctx context.Context) IScenePromptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IScenePromptDo
	WriteDB() IScenePromptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IScenePromptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IScenePromptDo
	Not(conds ...gen.Condition) IScenePromptDo
	Or(conds ...gen.Condition) IScenePromptDo
	Select(conds ...field.Expr) IScenePromptDo
	Where(conds ...gen.Condition) IScenePromptDo
	Order(conds ...field.Expr) IScenePromptDo
	Distinct(cols ...field.Expr) IScenePromptDo
	Omit(cols ...field.Expr) IScenePromptDo
	Join(table schema.Tabler, on ...field.Expr) IScenePromptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IScenePromptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IScenePromptDo
	Group(cols ...field.Expr) IScenePromptDo
	Having(conds ...gen.Condition) IScenePromptDo
	Limit(limit int) IScenePromptDo
	Offset(offset int) IScenePromptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IScenePromptDo
	Unscoped() IScenePromptDo
	Create(values ...*entity.ScenePrompt) error
	CreateInBatches(values []*entity.ScenePrompt, batchSize int) error
	Save(values ...*entity.ScenePrompt) error
	First() (*entity.ScenePrompt, error)
	Take() (*entity.ScenePrompt, error)
	Last() (*entity.ScenePrompt, error)
	Find() ([]*entity.ScenePrompt, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ScenePrompt, err error)
	FindInBatches(result *[]*entity.ScenePrompt, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ScenePrompt) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IScenePromptDo
	Assign(attrs ...field.AssignExpr) IScenePromptDo
	Joins(fields ...field.RelationField) IScenePromptDo
	Preload(fields ...field.RelationField) IScenePromptDo
	FirstOrInit() (*entity.ScenePrompt, error)
	FirstOrCreate() (*entity.ScenePrompt, error)
	FindByPage(offset int, limit int) (result []*entity.ScenePrompt, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IScenePromptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s scenePromptDo) Debug() IScenePromptDo {
	return s.withDO(s.DO.Debug())
}

func (s scenePromptDo) WithContext(ctx context.Context) IScenePromptDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scenePromptDo) ReadDB() IScenePromptDo {
	return s.Clauses(dbresolver.Read)
}

func (s scenePromptDo) WriteDB() IScenePromptDo {
	return s.Clauses(dbresolver.Write)
}

func (s scenePromptDo) Session(config *gorm.Session) IScenePromptDo {
	return s.withDO(s.DO.Session(config))
}

func (s scenePromptDo) Clauses(conds ...clause.Expression) IScenePromptDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scenePromptDo) Returning(value interface{}, columns ...string) IScenePromptDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scenePromptDo) Not(conds ...gen.Condition) IScenePromptDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scenePromptDo) Or(conds ...gen.Condition) IScenePromptDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scenePromptDo) Select(conds ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scenePromptDo) Where(conds ...gen.Condition) IScenePromptDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scenePromptDo) Order(conds ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scenePromptDo) Distinct(cols ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scenePromptDo) Omit(cols ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scenePromptDo) Join(table schema.Tabler, on ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scenePromptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scenePromptDo) RightJoin(table schema.Tabler, on ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scenePromptDo) Group(cols ...field.Expr) IScenePromptDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scenePromptDo) Having(conds ...gen.Condition) IScenePromptDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scenePromptDo) Limit(limit int) IScenePromptDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scenePromptDo) Offset(offset int) IScenePromptDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scenePromptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IScenePromptDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scenePromptDo) Unscoped() IScenePromptDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scenePromptDo) Create(values ...*entity.ScenePrompt) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scenePromptDo) CreateInBatches(values []*entity.ScenePrompt, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scenePromptDo) Save(values ...*entity.ScenePrompt) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scenePromptDo) First() (*entity.ScenePrompt, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ScenePrompt), nil
	}
}

func (s scenePromptDo) Take() (*entity.ScenePrompt, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ScenePrompt), nil
	}
}

func (s scenePromptDo) Last() (*entity.ScenePrompt, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ScenePrompt), nil
	}
}

func (s scenePromptDo) Find() ([]*entity.ScenePrompt, error) {
	result, err := s.DO.Find()
	return result.([]*entity.ScenePrompt), err
}

func (s scenePromptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ScenePrompt, err error) {
	buf := make([]*entity.ScenePrompt, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scenePromptDo) FindInBatches(result *[]*entity.ScenePrompt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scenePromptDo) Attrs(attrs ...field.AssignExpr) IScenePromptDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scenePromptDo) Assign(attrs ...field.AssignExpr) IScenePromptDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scenePromptDo) Joins(fields ...field.RelationField) IScenePromptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scenePromptDo) Preload(fields ...field.RelationField) IScenePromptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scenePromptDo) FirstOrInit() (*entity.ScenePrompt, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ScenePrompt), nil
	}
}

func (s scenePromptDo) FirstOrCreate() (*entity.ScenePrompt, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ScenePrompt), nil
	}
}

func (s scenePromptDo) FindByPage(offset int, limit int) (result []*entity.ScenePrompt, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scenePromptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scenePromptDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scenePromptDo) Delete(models ...*entity.ScenePrompt) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scenePromptDo) withDO(do gen.Dao) *scenePromptDo {
	s.DO = *do.(*gen.DO)
	return s
}
