// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newToolCallToken(db *gorm.DB, opts ...gen.DOOption) toolCallToken {
	_toolCallToken := toolCallToken{}

	_toolCallToken.toolCallTokenDo.UseDB(db, opts...)
	_toolCallToken.toolCallTokenDo.UseModel(&entity.ToolCallToken{})

	tableName := _toolCallToken.toolCallTokenDo.TableName()
	_toolCallToken.ALL = field.NewAsterisk(tableName)
	_toolCallToken.Id = field.NewUint(tableName, "id")
	_toolCallToken.CreatedAt = field.NewTime(tableName, "created_at")
	_toolCallToken.UpdatedAt = field.NewTime(tableName, "updated_at")
	_toolCallToken.MessageId = field.NewUint(tableName, "message_id")
	_toolCallToken.Token = field.NewString(tableName, "token")
	_toolCallToken.ExpiredAt = field.NewTime(tableName, "expired_at")

	_toolCallToken.fillFieldMap()

	return _toolCallToken
}

type toolCallToken struct {
	toolCallTokenDo

	ALL       field.Asterisk
	Id        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	MessageId field.Uint
	Token     field.String
	ExpiredAt field.Time

	fieldMap map[string]field.Expr
}

func (t toolCallToken) Table(newTableName string) *toolCallToken {
	t.toolCallTokenDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t toolCallToken) As(alias string) *toolCallToken {
	t.toolCallTokenDo.DO = *(t.toolCallTokenDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *toolCallToken) updateTableName(table string) *toolCallToken {
	t.ALL = field.NewAsterisk(table)
	t.Id = field.NewUint(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.MessageId = field.NewUint(table, "message_id")
	t.Token = field.NewString(table, "token")
	t.ExpiredAt = field.NewTime(table, "expired_at")

	t.fillFieldMap()

	return t
}

func (t *toolCallToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *toolCallToken) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.Id
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["message_id"] = t.MessageId
	t.fieldMap["token"] = t.Token
	t.fieldMap["expired_at"] = t.ExpiredAt
}

func (t toolCallToken) clone(db *gorm.DB) toolCallToken {
	t.toolCallTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t toolCallToken) replaceDB(db *gorm.DB) toolCallToken {
	t.toolCallTokenDo.ReplaceDB(db)
	return t
}

type toolCallTokenDo struct{ gen.DO }

type IToolCallTokenDo interface {
	gen.SubQuery
	Debug() IToolCallTokenDo
	WithContext(ctx context.Context) IToolCallTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IToolCallTokenDo
	WriteDB() IToolCallTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IToolCallTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IToolCallTokenDo
	Not(conds ...gen.Condition) IToolCallTokenDo
	Or(conds ...gen.Condition) IToolCallTokenDo
	Select(conds ...field.Expr) IToolCallTokenDo
	Where(conds ...gen.Condition) IToolCallTokenDo
	Order(conds ...field.Expr) IToolCallTokenDo
	Distinct(cols ...field.Expr) IToolCallTokenDo
	Omit(cols ...field.Expr) IToolCallTokenDo
	Join(table schema.Tabler, on ...field.Expr) IToolCallTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IToolCallTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IToolCallTokenDo
	Group(cols ...field.Expr) IToolCallTokenDo
	Having(conds ...gen.Condition) IToolCallTokenDo
	Limit(limit int) IToolCallTokenDo
	Offset(offset int) IToolCallTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IToolCallTokenDo
	Unscoped() IToolCallTokenDo
	Create(values ...*entity.ToolCallToken) error
	CreateInBatches(values []*entity.ToolCallToken, batchSize int) error
	Save(values ...*entity.ToolCallToken) error
	First() (*entity.ToolCallToken, error)
	Take() (*entity.ToolCallToken, error)
	Last() (*entity.ToolCallToken, error)
	Find() ([]*entity.ToolCallToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ToolCallToken, err error)
	FindInBatches(result *[]*entity.ToolCallToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.ToolCallToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IToolCallTokenDo
	Assign(attrs ...field.AssignExpr) IToolCallTokenDo
	Joins(fields ...field.RelationField) IToolCallTokenDo
	Preload(fields ...field.RelationField) IToolCallTokenDo
	FirstOrInit() (*entity.ToolCallToken, error)
	FirstOrCreate() (*entity.ToolCallToken, error)
	FindByPage(offset int, limit int) (result []*entity.ToolCallToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IToolCallTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t toolCallTokenDo) Debug() IToolCallTokenDo {
	return t.withDO(t.DO.Debug())
}

func (t toolCallTokenDo) WithContext(ctx context.Context) IToolCallTokenDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t toolCallTokenDo) ReadDB() IToolCallTokenDo {
	return t.Clauses(dbresolver.Read)
}

func (t toolCallTokenDo) WriteDB() IToolCallTokenDo {
	return t.Clauses(dbresolver.Write)
}

func (t toolCallTokenDo) Session(config *gorm.Session) IToolCallTokenDo {
	return t.withDO(t.DO.Session(config))
}

func (t toolCallTokenDo) Clauses(conds ...clause.Expression) IToolCallTokenDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t toolCallTokenDo) Returning(value interface{}, columns ...string) IToolCallTokenDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t toolCallTokenDo) Not(conds ...gen.Condition) IToolCallTokenDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t toolCallTokenDo) Or(conds ...gen.Condition) IToolCallTokenDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t toolCallTokenDo) Select(conds ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t toolCallTokenDo) Where(conds ...gen.Condition) IToolCallTokenDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t toolCallTokenDo) Order(conds ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t toolCallTokenDo) Distinct(cols ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t toolCallTokenDo) Omit(cols ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t toolCallTokenDo) Join(table schema.Tabler, on ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t toolCallTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t toolCallTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t toolCallTokenDo) Group(cols ...field.Expr) IToolCallTokenDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t toolCallTokenDo) Having(conds ...gen.Condition) IToolCallTokenDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t toolCallTokenDo) Limit(limit int) IToolCallTokenDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t toolCallTokenDo) Offset(offset int) IToolCallTokenDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t toolCallTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IToolCallTokenDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t toolCallTokenDo) Unscoped() IToolCallTokenDo {
	return t.withDO(t.DO.Unscoped())
}

func (t toolCallTokenDo) Create(values ...*entity.ToolCallToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t toolCallTokenDo) CreateInBatches(values []*entity.ToolCallToken, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t toolCallTokenDo) Save(values ...*entity.ToolCallToken) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t toolCallTokenDo) First() (*entity.ToolCallToken, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ToolCallToken), nil
	}
}

func (t toolCallTokenDo) Take() (*entity.ToolCallToken, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ToolCallToken), nil
	}
}

func (t toolCallTokenDo) Last() (*entity.ToolCallToken, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ToolCallToken), nil
	}
}

func (t toolCallTokenDo) Find() ([]*entity.ToolCallToken, error) {
	result, err := t.DO.Find()
	return result.([]*entity.ToolCallToken), err
}

func (t toolCallTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ToolCallToken, err error) {
	buf := make([]*entity.ToolCallToken, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t toolCallTokenDo) FindInBatches(result *[]*entity.ToolCallToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t toolCallTokenDo) Attrs(attrs ...field.AssignExpr) IToolCallTokenDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t toolCallTokenDo) Assign(attrs ...field.AssignExpr) IToolCallTokenDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t toolCallTokenDo) Joins(fields ...field.RelationField) IToolCallTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t toolCallTokenDo) Preload(fields ...field.RelationField) IToolCallTokenDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t toolCallTokenDo) FirstOrInit() (*entity.ToolCallToken, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ToolCallToken), nil
	}
}

func (t toolCallTokenDo) FirstOrCreate() (*entity.ToolCallToken, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ToolCallToken), nil
	}
}

func (t toolCallTokenDo) FindByPage(offset int, limit int) (result []*entity.ToolCallToken, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t toolCallTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t toolCallTokenDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t toolCallTokenDo) Delete(models ...*entity.ToolCallToken) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *toolCallTokenDo) withDO(do gen.Dao) *toolCallTokenDo {
	t.DO = *do.(*gen.DO)
	return t
}
