// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newUnsettledToken(db *gorm.DB, opts ...gen.DOOption) unsettledToken {
	_unsettledToken := unsettledToken{}

	_unsettledToken.unsettledTokenDo.UseDB(db, opts...)
	_unsettledToken.unsettledTokenDo.UseModel(&entity.UnsettledToken{})

	tableName := _unsettledToken.unsettledTokenDo.TableName()
	_unsettledToken.ALL = field.NewAsterisk(tableName)
	_unsettledToken.Id = field.NewUint(tableName, "id")
	_unsettledToken.CreatedAt = field.NewTime(tableName, "created_at")
	_unsettledToken.UpdatedAt = field.NewTime(tableName, "updated_at")
	_unsettledToken.UserId = field.NewString(tableName, "user_id")
	_unsettledToken.Count_ = field.NewInt64(tableName, "count")

	_unsettledToken.fillFieldMap()

	return _unsettledToken
}

type unsettledToken struct {
	unsettledTokenDo

	ALL       field.Asterisk
	Id        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	UserId    field.String
	Count_    field.Int64

	fieldMap map[string]field.Expr
}

func (u unsettledToken) Table(newTableName string) *unsettledToken {
	u.unsettledTokenDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u unsettledToken) As(alias string) *unsettledToken {
	u.unsettledTokenDo.DO = *(u.unsettledTokenDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *unsettledToken) updateTableName(table string) *unsettledToken {
	u.ALL = field.NewAsterisk(table)
	u.Id = field.NewUint(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.UserId = field.NewString(table, "user_id")
	u.Count_ = field.NewInt64(table, "count")

	u.fillFieldMap()

	return u
}

func (u *unsettledToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *unsettledToken) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.Id
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["user_id"] = u.UserId
	u.fieldMap["count"] = u.Count_
}

func (u unsettledToken) clone(db *gorm.DB) unsettledToken {
	u.unsettledTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u unsettledToken) replaceDB(db *gorm.DB) unsettledToken {
	u.unsettledTokenDo.ReplaceDB(db)
	return u
}

type unsettledTokenDo struct{ gen.DO }

type IUnsettledTokenDo interface {
	gen.SubQuery
	Debug() IUnsettledTokenDo
	WithContext(ctx context.Context) IUnsettledTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUnsettledTokenDo
	WriteDB() IUnsettledTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUnsettledTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUnsettledTokenDo
	Not(conds ...gen.Condition) IUnsettledTokenDo
	Or(conds ...gen.Condition) IUnsettledTokenDo
	Select(conds ...field.Expr) IUnsettledTokenDo
	Where(conds ...gen.Condition) IUnsettledTokenDo
	Order(conds ...field.Expr) IUnsettledTokenDo
	Distinct(cols ...field.Expr) IUnsettledTokenDo
	Omit(cols ...field.Expr) IUnsettledTokenDo
	Join(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo
	Group(cols ...field.Expr) IUnsettledTokenDo
	Having(conds ...gen.Condition) IUnsettledTokenDo
	Limit(limit int) IUnsettledTokenDo
	Offset(offset int) IUnsettledTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUnsettledTokenDo
	Unscoped() IUnsettledTokenDo
	Create(values ...*entity.UnsettledToken) error
	CreateInBatches(values []*entity.UnsettledToken, batchSize int) error
	Save(values ...*entity.UnsettledToken) error
	First() (*entity.UnsettledToken, error)
	Take() (*entity.UnsettledToken, error)
	Last() (*entity.UnsettledToken, error)
	Find() ([]*entity.UnsettledToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.UnsettledToken, err error)
	FindInBatches(result *[]*entity.UnsettledToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.UnsettledToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUnsettledTokenDo
	Assign(attrs ...field.AssignExpr) IUnsettledTokenDo
	Joins(fields ...field.RelationField) IUnsettledTokenDo
	Preload(fields ...field.RelationField) IUnsettledTokenDo
	FirstOrInit() (*entity.UnsettledToken, error)
	FirstOrCreate() (*entity.UnsettledToken, error)
	FindByPage(offset int, limit int) (result []*entity.UnsettledToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUnsettledTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u unsettledTokenDo) Debug() IUnsettledTokenDo {
	return u.withDO(u.DO.Debug())
}

func (u unsettledTokenDo) WithContext(ctx context.Context) IUnsettledTokenDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u unsettledTokenDo) ReadDB() IUnsettledTokenDo {
	return u.Clauses(dbresolver.Read)
}

func (u unsettledTokenDo) WriteDB() IUnsettledTokenDo {
	return u.Clauses(dbresolver.Write)
}

func (u unsettledTokenDo) Session(config *gorm.Session) IUnsettledTokenDo {
	return u.withDO(u.DO.Session(config))
}

func (u unsettledTokenDo) Clauses(conds ...clause.Expression) IUnsettledTokenDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u unsettledTokenDo) Returning(value interface{}, columns ...string) IUnsettledTokenDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u unsettledTokenDo) Not(conds ...gen.Condition) IUnsettledTokenDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u unsettledTokenDo) Or(conds ...gen.Condition) IUnsettledTokenDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u unsettledTokenDo) Select(conds ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u unsettledTokenDo) Where(conds ...gen.Condition) IUnsettledTokenDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u unsettledTokenDo) Order(conds ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u unsettledTokenDo) Distinct(cols ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u unsettledTokenDo) Omit(cols ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u unsettledTokenDo) Join(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u unsettledTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u unsettledTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u unsettledTokenDo) Group(cols ...field.Expr) IUnsettledTokenDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u unsettledTokenDo) Having(conds ...gen.Condition) IUnsettledTokenDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u unsettledTokenDo) Limit(limit int) IUnsettledTokenDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u unsettledTokenDo) Offset(offset int) IUnsettledTokenDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u unsettledTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUnsettledTokenDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u unsettledTokenDo) Unscoped() IUnsettledTokenDo {
	return u.withDO(u.DO.Unscoped())
}

func (u unsettledTokenDo) Create(values ...*entity.UnsettledToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u unsettledTokenDo) CreateInBatches(values []*entity.UnsettledToken, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u unsettledTokenDo) Save(values ...*entity.UnsettledToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u unsettledTokenDo) First() (*entity.UnsettledToken, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UnsettledToken), nil
	}
}

func (u unsettledTokenDo) Take() (*entity.UnsettledToken, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UnsettledToken), nil
	}
}

func (u unsettledTokenDo) Last() (*entity.UnsettledToken, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UnsettledToken), nil
	}
}

func (u unsettledTokenDo) Find() ([]*entity.UnsettledToken, error) {
	result, err := u.DO.Find()
	return result.([]*entity.UnsettledToken), err
}

func (u unsettledTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.UnsettledToken, err error) {
	buf := make([]*entity.UnsettledToken, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u unsettledTokenDo) FindInBatches(result *[]*entity.UnsettledToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u unsettledTokenDo) Attrs(attrs ...field.AssignExpr) IUnsettledTokenDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u unsettledTokenDo) Assign(attrs ...field.AssignExpr) IUnsettledTokenDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u unsettledTokenDo) Joins(fields ...field.RelationField) IUnsettledTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u unsettledTokenDo) Preload(fields ...field.RelationField) IUnsettledTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u unsettledTokenDo) FirstOrInit() (*entity.UnsettledToken, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UnsettledToken), nil
	}
}

func (u unsettledTokenDo) FirstOrCreate() (*entity.UnsettledToken, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UnsettledToken), nil
	}
}

func (u unsettledTokenDo) FindByPage(offset int, limit int) (result []*entity.UnsettledToken, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u unsettledTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u unsettledTokenDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u unsettledTokenDo) Delete(models ...*entity.UnsettledToken) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *unsettledTokenDo) withDO(do gen.Dao) *unsettledTokenDo {
	u.DO = *do.(*gen.DO)
	return u
}
