// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"rag-new/internal/entity"
)

func newUserFile(db *gorm.DB, opts ...gen.DOOption) userFile {
	_userFile := userFile{}

	_userFile.userFileDo.UseDB(db, opts...)
	_userFile.userFileDo.UseModel(&entity.UserFile{})

	tableName := _userFile.userFileDo.TableName()
	_userFile.ALL = field.NewAsterisk(tableName)
	_userFile.Id = field.NewUint(tableName, "id")
	_userFile.CreatedAt = field.NewTime(tableName, "created_at")
	_userFile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userFile.UserId = field.NewString(tableName, "user_id")
	_userFile.FileId = field.NewUint(tableName, "file_id")
	_userFile.File = userFileBelongsToFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("File", "entity.File"),
	}

	_userFile.fillFieldMap()

	return _userFile
}

type userFile struct {
	userFileDo

	ALL       field.Asterisk
	Id        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	UserId    field.String
	FileId    field.Uint
	File      userFileBelongsToFile

	fieldMap map[string]field.Expr
}

func (u userFile) Table(newTableName string) *userFile {
	u.userFileDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userFile) As(alias string) *userFile {
	u.userFileDo.DO = *(u.userFileDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userFile) updateTableName(table string) *userFile {
	u.ALL = field.NewAsterisk(table)
	u.Id = field.NewUint(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.UserId = field.NewString(table, "user_id")
	u.FileId = field.NewUint(table, "file_id")

	u.fillFieldMap()

	return u
}

func (u *userFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userFile) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.Id
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["user_id"] = u.UserId
	u.fieldMap["file_id"] = u.FileId

}

func (u userFile) clone(db *gorm.DB) userFile {
	u.userFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userFile) replaceDB(db *gorm.DB) userFile {
	u.userFileDo.ReplaceDB(db)
	return u
}

type userFileBelongsToFile struct {
	db *gorm.DB

	field.RelationField
}

func (a userFileBelongsToFile) Where(conds ...field.Expr) *userFileBelongsToFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userFileBelongsToFile) WithContext(ctx context.Context) *userFileBelongsToFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userFileBelongsToFile) Session(session *gorm.Session) *userFileBelongsToFile {
	a.db = a.db.Session(session)
	return &a
}

func (a userFileBelongsToFile) Model(m *entity.UserFile) *userFileBelongsToFileTx {
	return &userFileBelongsToFileTx{a.db.Model(m).Association(a.Name())}
}

type userFileBelongsToFileTx struct{ tx *gorm.Association }

func (a userFileBelongsToFileTx) Find() (result *entity.File, err error) {
	return result, a.tx.Find(&result)
}

func (a userFileBelongsToFileTx) Append(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userFileBelongsToFileTx) Replace(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userFileBelongsToFileTx) Delete(values ...*entity.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userFileBelongsToFileTx) Clear() error {
	return a.tx.Clear()
}

func (a userFileBelongsToFileTx) Count() int64 {
	return a.tx.Count()
}

type userFileDo struct{ gen.DO }

type IUserFileDo interface {
	gen.SubQuery
	Debug() IUserFileDo
	WithContext(ctx context.Context) IUserFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserFileDo
	WriteDB() IUserFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserFileDo
	Not(conds ...gen.Condition) IUserFileDo
	Or(conds ...gen.Condition) IUserFileDo
	Select(conds ...field.Expr) IUserFileDo
	Where(conds ...gen.Condition) IUserFileDo
	Order(conds ...field.Expr) IUserFileDo
	Distinct(cols ...field.Expr) IUserFileDo
	Omit(cols ...field.Expr) IUserFileDo
	Join(table schema.Tabler, on ...field.Expr) IUserFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserFileDo
	Group(cols ...field.Expr) IUserFileDo
	Having(conds ...gen.Condition) IUserFileDo
	Limit(limit int) IUserFileDo
	Offset(offset int) IUserFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFileDo
	Unscoped() IUserFileDo
	Create(values ...*entity.UserFile) error
	CreateInBatches(values []*entity.UserFile, batchSize int) error
	Save(values ...*entity.UserFile) error
	First() (*entity.UserFile, error)
	Take() (*entity.UserFile, error)
	Last() (*entity.UserFile, error)
	Find() ([]*entity.UserFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.UserFile, err error)
	FindInBatches(result *[]*entity.UserFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.UserFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserFileDo
	Assign(attrs ...field.AssignExpr) IUserFileDo
	Joins(fields ...field.RelationField) IUserFileDo
	Preload(fields ...field.RelationField) IUserFileDo
	FirstOrInit() (*entity.UserFile, error)
	FirstOrCreate() (*entity.UserFile, error)
	FindByPage(offset int, limit int) (result []*entity.UserFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userFileDo) Debug() IUserFileDo {
	return u.withDO(u.DO.Debug())
}

func (u userFileDo) WithContext(ctx context.Context) IUserFileDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userFileDo) ReadDB() IUserFileDo {
	return u.Clauses(dbresolver.Read)
}

func (u userFileDo) WriteDB() IUserFileDo {
	return u.Clauses(dbresolver.Write)
}

func (u userFileDo) Session(config *gorm.Session) IUserFileDo {
	return u.withDO(u.DO.Session(config))
}

func (u userFileDo) Clauses(conds ...clause.Expression) IUserFileDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userFileDo) Returning(value interface{}, columns ...string) IUserFileDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userFileDo) Not(conds ...gen.Condition) IUserFileDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userFileDo) Or(conds ...gen.Condition) IUserFileDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userFileDo) Select(conds ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userFileDo) Where(conds ...gen.Condition) IUserFileDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userFileDo) Order(conds ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userFileDo) Distinct(cols ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userFileDo) Omit(cols ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userFileDo) Join(table schema.Tabler, on ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userFileDo) Group(cols ...field.Expr) IUserFileDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userFileDo) Having(conds ...gen.Condition) IUserFileDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userFileDo) Limit(limit int) IUserFileDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userFileDo) Offset(offset int) IUserFileDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFileDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userFileDo) Unscoped() IUserFileDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userFileDo) Create(values ...*entity.UserFile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userFileDo) CreateInBatches(values []*entity.UserFile, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userFileDo) Save(values ...*entity.UserFile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userFileDo) First() (*entity.UserFile, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UserFile), nil
	}
}

func (u userFileDo) Take() (*entity.UserFile, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UserFile), nil
	}
}

func (u userFileDo) Last() (*entity.UserFile, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UserFile), nil
	}
}

func (u userFileDo) Find() ([]*entity.UserFile, error) {
	result, err := u.DO.Find()
	return result.([]*entity.UserFile), err
}

func (u userFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.UserFile, err error) {
	buf := make([]*entity.UserFile, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userFileDo) FindInBatches(result *[]*entity.UserFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userFileDo) Attrs(attrs ...field.AssignExpr) IUserFileDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userFileDo) Assign(attrs ...field.AssignExpr) IUserFileDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userFileDo) Joins(fields ...field.RelationField) IUserFileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userFileDo) Preload(fields ...field.RelationField) IUserFileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userFileDo) FirstOrInit() (*entity.UserFile, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UserFile), nil
	}
}

func (u userFileDo) FirstOrCreate() (*entity.UserFile, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.UserFile), nil
	}
}

func (u userFileDo) FindByPage(offset int, limit int) (result []*entity.UserFile, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userFileDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userFileDo) Delete(models ...*entity.UserFile) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userFileDo) withDO(do gen.Dao) *userFileDo {
	u.DO = *do.(*gen.DO)
	return u
}
