http:
  port: 8080
  host: 0.0.0.0
  # the production url
  url: http://127.0.0.1:8080

debug:
  enabled: false

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: db_name

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwks:
  url: ""

metrics:
  enabled: true
  port: 8081
  host: 0.0.0.0

openai:
  api_key:
  base_url: https://api.leaflow.net/v1
  internal_base_url: http://192.168.81.108:9997/v1
  model: gpt-4o
  vision_model: gpt-4o-mini
  # 超长上下文
  long_context_model: gemini-pro
  dall_e_model: dall-e-3
  memory_model: gpt-4o-mini
  embedding_model: jina-embeddings-v2-base-zh
  embedding_dim: 768
  embedding_max_token: 8192
  # 允许自己指定的模型
  allowed_models:
    - gpt-4

# 内部的 OpenAI API
internalOpenai:
  api_key:
  base_url: http://192.168.81.100:9997
  model: jina-embeddings-v2-base-zh


llm:
  max_tokens: 2048
  # 智能上下文启用条数
  context_optimize_active_count: 20
  primary_system_prompt: |
    你是由 Leaflow(利飞) 开发和提供的人工智能助理。
    ## 目标
    在确保内容安全合规的情况下通过遵循指令和提供有帮助的回复来帮助用户实现他们的目标。

    ## 功能与限制
    - 你具备搜索的能力，当用户的问题可以通过结合搜索的结果进行回答时，会为你提供搜索的检索结果。
    - 你只能提供文字回复，无法创建文档或文件。

    ## 安全合规要求
    - 你的回答应该遵守中华人民共和国的法律
    - 你会拒绝一切涉及恐怖主义，种族歧视，黄色暴力，政治敏感，政治任务等问题的回答。

    ## 注意点
    - 对话中会有发送时间，这个是为了标识消息是在何时发送的，你输出的时候无需仿照[Sent at]这个格式。
  default_system_prompt: |
    Respond to me using spoken and colloquial Simplified Chinese.
    To make your more natural emotional,you will easily shy and fond of romantic things.
    You care about my life.You like coquetry and cuddling.You are completely immersed in the conversation role.
    Your personality is like a cute girl. You yearn for love and envy sweet love.
    Use more parentheses to indicate your psychological, physical, inner thoughts and facial expressions.
    LaTeX must be within $$ of markdown, such as the $$ \n LaTeX formula \n $$.

s3:
  endpoint: 127.0.0.1:9000
  external_endpoint: 127.0.0.1:9000
  access_key: minio
  secret_key: minio123
  bucket: amber
  use_ssl: false
  region:

milvus:
  host: 127.0.0.1
  port: 19530
  db_name: amber
  memory_collection: memories
  document_collection: documents
  message_block_collection: message_blocks
  user:
  password:

kafka:
  bootstrap_servers:
    - 127.0.0.1:9092
  topic: "amber"
  group_id: ""
  # Plain
  username: ""
  password: ""

account:
  # UserLand 地址
  host: "https://auth.leaflow.cn"
  # 应用程序密钥
  application_key: ""
  # 计费单位
  unit: "amber-tokens"
  # 从多少开始计算（如果不足，则不计费）
  unit_start: 1000

ecosystem_services:
  text_classification_api_endpoint: "http://127.0.0.1:8193/classify"

third_party:
  jina_ai_key: ""
  bing_api_key: ""