http:
  port: 8080
  host: 0.0.0.0
  # the production url
  url: http://127.0.0.1:8080

debug:
  enabled: false

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: db_name

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwks:
  url: ""

metrics:
  enabled: true
  port: 8081
  host: 0.0.0.0

openai:
  api_key:
  base_url: https://api.leaflow.net/v1
  model: gpt-4o
  vision_model: gpt-4o-mini
  # 超长上下文
  long_context_model: gemini-pro
  dall_e_model: dall-e-3
  # 允许自己指定的模型
  allowed_models:
    - gpt-4

llm:
  max_tokens: 2048

s3:
  endpoint: 127.0.0.1:9000
  external_endpoint: 127.0.0.1:9000
  access_key: minio
  secret_key: minio123
  bucket: amber
  use_ssl: false
  region:
